### ISSUE TITLE
Pruning default certificate authorities section needs some love :)

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/macOS-Security-and-Privacy-Guide#113]
https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#certificate-authorities

Even after reading the referenced materials, it is not clear to me which CAs can be removed and which can be trusted and how to properly remove them at the OS level. In Firefox, this is much easier, as you can simply deselect the CA and it's abilities. OS X CA store seems a bit more involved. Any further advice for this section?

**Comment by drduh** [comment]
I've been contemplating this for a little while now. Unfortunately, I haven't come up with a programmatic way of pruning system CAs: each individual certificate's trust must be modified by hand with Keychain Access, an onerous and annoying process. At a minimum, we could enumerate the list of trusted certificates by default and categorize them, maybe even assign a likelihood of their usefulness (I would guess most users don't benefit from trusting the Hongkong Post Root CA, for example).

So there is certainly an opportunity for improving this section, but care must be taken to explain the implications of removing trust for certain CAs. Weighing this with the potential benefit gained from doing so has put this work at a lower priority for me, but I concede it's worthwhile.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
I think the proper way to tackle this is to have a handful at least (preferably much more) of users disable all certificates and selectively reenable them every time they are blocked. Take the  final list of what people still have disabled and use that as the list to keep disabled because most people won't be utilizing them.

**Comment by drduh** [comment]
I'm still looking for a script-able, programmatic way to manage the system root CAs on OS X. One way might be to copy all root CAs the System keychain and mark them as "untrusted", enabling certificates one by one, or "allowing" them in a similar vein to Little Snitch.

This could be a fun exercise or weekend project to complete in Objective-C - see https://developer.apple.com/library/mac/documentation/Security/Reference/keychainservices/

**Comment by drduh** [comment]
I don't know of a feasible, programmatic way to do this now, so closing.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Can I suggest an easy start? How about removing some international CAs? Eg. if the user is in the USA, then removing all China CAs, etc?

**Comment by drduh** [comment]
I will think about some way to explain how a user could make her own determination. Thanks for the suggestion.

**Comment by adamdecaf** [comment]
I just landed support for this in my tool, [`cert-manage`](https://github.com/adamdecaf/cert-manage), which I've love for people to try out.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
@adamdecaf can you add the ability to prune root CA authorities by geographic region? Eg. Disable all  Asia CAs if the user is in North America, etc? I think this would be a great start and take the primary discussion to your issue tracker and revisit here when completed.

**Comment by adamdecaf** [comment]
> can you add the ability to prune root CA authorities by geographic region? Eg. Disable all Asia CAs if the user is in North America, etc?

I've thought about that, but not quite sure how best to do build those lists. Are you thinking just off of `countryName` in the CA cert? I created https://github.com/adamdecaf/cert-manage/issues/161 to track this.
