### ISSUE TITLE
S/MIME-encrypted disk images

### ISSUE THREAD

**Issue by JayBrown** [drduh/macOS-Security-and-Privacy-Guide#131]
Little-known (and even less-used) feature of `hdiutil`: encrypt .dmg, .sparsebundle & .sparseimage with public key(s) of S/MIME certificate(s) instead of passwords, very much like the PGPdisk many years ago. Arranged into a workflow/script on my page (DiMaGo): https://github.com/JayBrown/DiMaGo It's still a work in progress, but it works.

**Comment by drduh** [comment]
That's pretty cool. You are welcome to submit a PR to reference your project, or I can, when I get around to it.

**Comment by JayBrown** [comment]
I can do that, but I'll wait just a little longer, because the next update will be important: it currently scans for public keys every time the user wants to use one to encrypt, but v1.5.0 will instead scan once a day (using a LaunchAgent) and write the results to prefs, with an additional manual rescan option.

**Comment by drduh** [comment]
Sounds good, just send a pull request along when you're ready. I'll close this issue out for now.
