### ISSUE TITLE
Homebrew: Mention additional security options and fix broken links

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/macOS-Security-and-Privacy-Guide#138]
Options:

HOMEBREW_NO_INSECURE_REDIRECT=1
HOMEBREW_CASK_OPTS=--require-sha
HOMEBREW_NO_ANALYTICS=1

These links are bad:

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Installation.md

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md

**Comment by Danrancan** [comment]
How do I go about activating these rules in Homebrew?

HOMEBREW_NO_INSECURE_REDIRECT=1
HOMEBREW_CASK_OPTS=--require-sha


Are they commands or lines in some file?
