### ISSUE TITLE
[Passwords] -- Change LANG= to LC_ALL=

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/macOS-Security-and-Privacy-Guide#144]
...otherwise you will get "tr: Illegal byte sequence"

**Comment by drduh** [comment]
I don't get any error with LANG:

```
$ LANG=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 40 | head -n 1
78Z9X0wbclZ6yNlze3OfbauWcJvJYWF1Xm4QPVBQ

$ LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 40 | head -n 1
BLmLNsEPFut7atBFmjp0kIkZ0PL8VRUZvSsrFxYD

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2657
```

Are you using a custom version of `tr`?

**Comment by octocracy** [comment]
csh, tcsh, and fish all need `env` prefixed in front of `LANG=C`

**Comment by drduh** [comment]
Please send a pull request with a suggested fix if this is a problem. I can't reproduce the issue with zsh nor bash.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
The standard tr with macos 10.12.2 doesn't work with LANG=C it appears? Might be a new issue? Can you confirm on 10.12.2?

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

$ which tr
/usr/bin/tr

$ LANG=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
tr: Illegal byte sequence

$ which gtr
/usr/local/bin/gtr

$ LANG=C gtr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
dnS1SDnIw7qsvi1V

To ensure it works, using LC_ALL appears to be sufficient.

$ LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
hD6VU36b1A1WFSPo

**Comment by danyalaytekin** [comment]
How come the variable was removed entirely?  I've learned something from your conversation though and have settled for `C`.  Thanks

```console
$ tr -dc '[:graph:]' < /dev/urandom | fold -w 20 | head -1
tr: Illegal byte sequence

$ LC_ALL=en_US !-1
tr: Illegal byte sequence

$ LC_ALL=en_UK !-2
w!Yl]7{^.v9gef^bH@kU

$ LC_ALL=C !-3
j;N?ojC\DAD#D,U,eH'6
```
