### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by Eitot** [drduh/macOS-Security-and-Privacy-Guide#148]
Have you considered turning your guide into a Jekyll page?

**Comment by vsaw** [comment]
For further reference read this section on project pages: https://help.github.com/articles/user-organization-and-project-pages/#project-pages

As pages are built by GitHub from Markdown sources the current mode of collaboration will remain the same.  It is however a great way to present the content in a more user friendly way.

**Comment by reclaimer** [comment]
Hmm, out of curiosity: what's the difference between GitHub's rendering of the markdown file, and the resulting Jekyll page?

**Comment by Eitot** [comment]
I would not do this purely for Markdown rendering. However, the overall presentation can be made a bit more user friendly and focussed by hiding the repository and GitHub interface and tweaking the layout. You can also turn the large README.md into a collection of smaller Markdown files and still render them all as one document, if desired. This makes collaboration easier as well.

**Comment by vsaw** [comment]
@reclaimer GitHub pages are powered by [Jekyll](https://jekyllrb.com/) which is a nice way to turn Markdown files into HTML pages.

So you still create your content in Markdown, which gets then rendered into HTML by Jekyll and then served to the user. This would for example easily allow to split the Guide into different sub-chapters and having proper layout with Breadcrumbs/TOC etc. which makes it easier to browse compared to the "one giant file" it is right now.

GitHub Pages is basically just a hosting service by GitHub, nicely integrated into the GitHub Worflow which for example automatically builds your webpage after each commit to your repository.

**Comment by reclaimer** [comment]
Oh yeah, I know all that. I just thought that's basically going to be the same as the MD file that gets rendered as a README here. But sure, chapters and TOC would be nice.

**Comment by drduh** [comment]
I did have a look at Jekyll and it's nice to be able to convert Markdown to HTML. I put this guide on GitHub so that I wouldn't have to keep maintaining it, and so others could check my work.

I haven't got the time to mirror and host it elsewhere right now. However, I think the license allows others to do that; if not, consider it allowed.

**Comment by vsaw** [comment]
@drduh For your information: [This fork here](http://www.vsaw.eu/OS-X-Security-and-Privacy-Guide/) literally took me 30 seconds to create using the [GitHub Automatic Page Generator](https://help.github.com/articles/creating-pages-with-the-automatic-generator/#the-automatic-page-generator).  It is completely hosted by GitHub and automatically generated from the [source in git](https://github.com/vsaw/OS-X-Security-and-Privacy-Guide).

So in summary:

- Super fast to set up a first version.
- Possibility to improve pages & readability
- Same contribution and maintenance as before
- No mirroring of sources required
- No extra hosting effort

Therefore, the way I see it, worst case is to have the README.md served via the GitHub front end and as a HTML page.  The upside is once you enable github pages the HTML version of the guide can be extended.  Therefore, give it a though ;-)

**Comment by reclaimer** [comment]
@vsaw Once the guide is updated, does the Jekyll version get updated as well? I mean, if we split this into files/pages, can you tell the Automatic Page Generator to rebuild the thing, with TOC as well?

**Comment by vsaw** [comment]
@reclaimer Yes.  The whole page get's rebuilt on every commit.  Regardless of which file got updated.
