### ISSUE TITLE
Document how to use macOS without an AppleID / iCloud / iTunes account

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/macOS-Security-and-Privacy-Guide#150]
It is possible. People are doing it and still able to download updates. It needs to be documented how this is done in a non-adhoc manner.

**Comment by drduh** [comment]
Well, what specifically should be documented? From my experience, everything "just works" without any Apple account, even App Store updates (less third-party applications).

**Comment by 9Yg1rxeSeha90ZU1** [comment]
I believe one is unable to download the Apple office suite applications updates and also xcode updates, to name a couple. May be others.

**Comment by reclaimer** [comment]
Do you still get software updates (i.e. macOS updates) without an App Store account?

**Comment by Eitot** [comment]
@reclaimer: Yes. Apple has muddied the water a bit, but system and security updates are still provided separately, albeit using the App Store application. Only App Store apps require an account. You can control these updates also separately with `softwareupdate`.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
No this does NOT apply updates for at least the following (tested and confirmed):
* Xcode
* Keynote
* Numbers
* Pages

**Comment by 9Yg1rxeSeha90ZU1** [comment]
So, softwareupdate is NOT a solution to this. The issue should therefore be re-opened.

**Comment by Eitot** [comment]
You still have not explained what the issue is. These four applications are distributed exclusively via the App Store, as such they require an Apple ID. Apple even states this in the fine print:
> Pages for Mac, Numbers for Mac, and Keynote for Mac are free on the Mac App Store for qualifying Mac computers purchased on or after October 1, 2013. macOS Sierra required. Downloading apps requires an Apple ID.

Apple does provide older versions of Xcode on developer.apple.com, but the download area is still accessible only with an Apple ID. Applications that originate in the App Store require an account, otherwise they would be available with `softwareupdate` or a standalone download at support.apple.com/downloads.

**Comment by stb-servicenow** [comment]
The other issue here is that there are times when free applications should be able to be acquired without the requirement for an AppleID .... prime example: when your company or organization has a security policy expressly forbidding the use of external (external to the company) user IDs or anything that connects to an external cloud.  I'm sure you can think of at least one or two organizations that have that situation.

The requirement for an Apple ID for just about everything to do with Apple is absurd, and in my humble view, Orwellian.  Of course, I tend to be as unhappy and vocal about the current state of computing technology and the internet as Richard Stallman.  I should be free to use a device or software however I want to, especially if I pay for it.
