### ISSUE TITLE
Force Linking to OpenSSL

### ISSUE THREAD

**Issue by marcus-cr** [drduh/macOS-Security-and-Privacy-Guide#158]
Keep getting this error when force linking OpenSSL on Sierra:

> Warning: Refusing to link: openssl
> Linking keg-only openssl means you may end up linking against the insecure, deprecated system OpenSSL while using the headers from Homebrew's openssl.
> Instead, pass the full include/library paths to your compiler e.g.:
>   -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

**Comment by Eitot** [comment]
See #39. You should not link OpenSSL. If you need it for building software, then you should modify the build configuration and link to Homebrew’s OpenSSL manually (as explained in your error message).

**Comment by marcus-cr** [comment]
I'm assuming this also applies to using it with instead of building software as well then. If so, please close for oversight. Proposing to better clarify the guide as well:

> If you're going to use OpenSSL on your Mac, download and install a recent version of OpenSSL with brew install openssl. Note, linking brew to be used in favor of /usr/bin/openssl may interfere with building software. See issue #39.
