### ISSUE TITLE
Brewed DNSmasq w/DNSSEC support may not require further dnsmasq.conf configuration?

### ISSUE THREAD

**Issue by marcus-cr** [drduh/macOS-Security-and-Privacy-Guide#160]
Both verification tests passed when dnsmasq was brewed `--with-dnssec`. Edited dnsmasq.conf with:

`# port=5369`
`server=127.0.0.1#5370`
`listen-address=127.0.0.1`
`# dnssec`
`# trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDD$`

The other suggested options were included. 

The `dig +dnssec icann.org` verification test and `dig www.dnssec-failed.org` test resulted in SERVFAIL when the DNSSEC options were commented in of dnsmasq.conf, e.g. `trust-anchor=`. 

When these same options are commented out, as in `# trust-anchor=`, the verification tests yielded NOERROR and SERVFAIL, respectively.

**Comment by marcus-cr** [comment]
I'd like to open up DNSSEC for discussion since there is apparent controversy regarding its use. Ended up abandoning it since I encountered some issues.

**Comment by drduh** [comment]
I, too, have experienced problems with DNSSEC and did disable the feature. I'll leave this open for a little while in case someone would like to make a strong case for continuing its use. Otherwise, I will remove or change the recommendation.

**Comment by dnwe** [comment]
Has anyone tried using [edgedns](https://github.com/jedisct1/edgedns/) by @jedisct1 in resolver mode as a replacement for dnsmasq?

**Comment by ryneeverett** [comment]
Could we be a little more explicit about "apparent controversy" and "some problems"?

**Comment by marcus-cr** [comment]
@ryneeverett 

### Controversy (not limited to the following):
> "DNSSEC uses outdated crypto methods, and could provide a dangerous entry point for government snooping."
> "...DNSSEC is very far from perfect. There is a [webpage](http://ianix.com/pub/dnssec-outages.html)[sic link] that tracks DNSSEC failures and outages – and there are many examples."
[The Register](http://www.theregister.co.uk/2015/03/18/is_the_dns_security_protocol_a_waste_of_everyones_time_and_money/)

### Problems (not limited to the following):
- Issue #160 (listed above due to DNSSEC not operating as expected with Homebrew version of `dnscrypt-proxy`
- [List of DNSSEC Outages from first referenced The Register article above](https://ianix.com/pub/dnssec-outages.html)
- Potential to be used as DDoS attack:
> "Using flaws in DNSSEC, it is possible to use that extra-large response as a way to amplify the number of packets sent – anywhere up to 100 times (though typically far less)."
[The Register](http://www.theregister.co.uk/2016/02/23/dnssec_more_problem_than_solution/)

**Comment by ryneeverett** [comment]
@marcus-cr Thanks!

**Comment by marcus-cr** [comment]
@dnwe I haven't used EdgeDNS. Is this something you're considering or have already implemented?

**Comment by dnwe** [comment]
@marcus-cr yes I've used it on one of my devices. Trivial to swap it in for dnsmasq, with a basic config pointing at dnscrypt-proxy.
```
[upstream]
type = "resolver"
servers = ["127.0.0.1:5355"]
strategy = "uniform"

[cache]
max_items = 250000
min_ttl = 60
max_ttl = 86400

[network]
udp_ports = 8
listen = "0.0.0.0:53"
```

**Comment by drduh** [comment]
Please send a PR if there's any need to follow-up on this issue.
