### ISSUE TITLE
previously linked website fix-macosx does not work anymore

### ISSUE THREAD

**Issue by karek314** [drduh/macOS-Security-and-Privacy-Guide#164]
As i have noticed previously linked website fix-macosx with it's script, does no longer works on Sierra, i have wrote simple script to handle removing "spotlight suggestions" in safari and system in simpler way. Script also disable useless agents & daemons and contains description of each functionality i've found running.

https://github.com/karek314/macOS-home-call-drop

Btw. Great job with this repository 👍

**Comment by drduh** [comment]
What do you mean by, that script no longer works?

**Comment by karek314** [comment]
Simply fix-macosx script linked in **macOS-Security-and-Privacy-Guide** does nothing. Did not applied changes for me. That's why i have linked mine which works with macOS Sierra.

**Comment by marvinrabe** [comment]
Also the SSL certificate of the website (https://fix-macosx.com/) has expired a few days ago.

So you will get an error from curl:
> curl: (60) SSL certificate problem: Invalid certificate chain

**Comment by drduh** [comment]
Paging @landonf

**Comment by landonf** [comment]
Thanks, I've deployed a renewed certificate. I'm afraid I haven't updated the instructions for later releases; I no longer use macOS as my desktop OS.

**Comment by sonyamamurin** [comment]
The site seems to be down?

**Comment by drduh** [comment]
https://fix-macosx.com/ looks to be working again. Closing.

**Comment by JimLoose** [comment]
if this is fixed you may remove this comment:
> Note This Web site and instructions may no longer work on macOS Sierra - see issue 164.
right here: https://github.com/drduh/macOS-Security-and-Privacy-Guide/blob/master/README.md#spotlight-suggestions

**Comment by DouglasUrner** [comment]
I get a connection refused at fix-macosx.com for both port 80 and 443.
