### ISSUE TITLE
Suggestion: include TCPBlock in the firewall section

### ISSUE THREAD

**Issue by 9Morello** [drduh/macOS-Security-and-Privacy-Guide#165]
TCPBlock is an application-based firewall for OS X that behaves much like TinyWall for Windows and AFWall+ for Android. Instead of IP addresses, you can use an application white list instead. Its a free (as in free beer) alternative to Little Snitch.

Thanks for this great guide.

**Comment by marcus-cr** [comment]
TCPBlock seems like a decent firewall, but was discontinued in 2014. IceFloor and Murus Lite are better free alternatives.

**Comment by drduh** [comment]
Pour one out for TCPBlock.
