### ISSUE TITLE
Unverified cliche damaging user objectivity present in overview

### ISSUE THREAD

**Issue by readnotify** [drduh/macOS-Security-and-Privacy-Guide#175]
Please remove this statement:

" There is no security silver bullet "

Most people nowdays do not think: this encourages them to avoid thinking for themselves in a highly negative way.

**Comment by reclaimer** [comment]
Doesn't this mean they **should** be more careful and objective? Knowing that there isn't a silver bullet means you are no longer susceptible to claims about perfect security, perfect tools, or tools that do it all.

**Comment by NiklasBr** [comment]
I wonder if @readnotify means that the sentence might get some people to give up thinking "oh, well, there isn't much I can do then". I can sort of agree and sort of disagree.

The case *for* that interpretation: The wording is a bit on the negative side, maybe consider changing it to something along the lines of "There are many small ways in which a system can become more secure, there are no silver bullets."?

The case *against*: This guide is aimed at power users who should understand that there are some ways to make a system more secure, but not exactly how, or why. This guide should help them.

**Comment by reclaimer** [comment]
Right, @NiklasBr. In that case it should be worded for clarity. There's no point in using a colloquialism where simple English will make it easier to understand. Amirite?
