### ISSUE TITLE
IP of visited site not protected by the HTTPS protocol, a solution?

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#176]
I red this article, not an April-fool...
https://www.scmagazine.com/windtalker-guesses-passwords-based-on-how-fingers-affect-wi-fi-readings

> By examining key metadata such as the IP address of the site a user is actively visiting (information that is not protected by the HTTPS protocol...

In general, not for that article, is there a solution to avoid that?
Except with a VPN, socks5 perhaps?

Thanks

**Comment by drduh** [comment]
This is by IP design. Even supposing there was a meaningful defense against this, it would be outside the scope of this guide, I think.
