### ISSUE TITLE
https://fix-macosx.com/fix-macosx.py SSL Certificate expired.

### ISSUE THREAD

**Issue by mattscilipoti** [drduh/macOS-Security-and-Privacy-Guide#180]
I'm hoping that you may know how to contact them to inform them of the expired certificate.  I sent an email to the whois registrant: fix-macosx.com@contactprivacy.com.

**Comment by TraderStf** [comment]
they are on https://github.com/fix-macosx/

**Comment by drduh** [comment]
Paging @landonf

**Comment by Eitot** [comment]
Why not remove the link? The fix is trivial and safer than using a Python script from an unknown source.

**Comment by drduh** [comment]
That Web site's certificate has been renewed.
