### ISSUE TITLE
InstallESD hashes for Sierra 10.12.1 build 16B2655

### ISSUE THREAD

**Issue by mrmeow1** [drduh/macOS-Security-and-Privacy-Guide#182]
Hello! Can you verify and add hashes for 10.12.1 build 16B2655 for me?

    MBP-admin:~ admin$ codesign -dvv /Applications/Install\ macOS\ Sierra.app
    Executable=/Applications/Install macOS Sierra.app/Contents/MacOS/InstallAssistant
    Identifier=com.apple.InstallAssistant.Sierra
    Format=app bundle with Mach-O thin (x86_64)
    CodeDirectory v=20200 size=417 flags=0x200(kill) hashes=5+5 location=embedded
    Signature size=4605
    Authority=Apple Mac OS Application Signing
    Authority=Apple Worldwide Developer Relations Certification Authority
    Authority=Apple Root CA
    Info.plist entries=30
    TeamIdentifier=K36BKF7T3D
    Sealed Resources version=2 rules=7 files=137
    Internal requirements count=1 size=124

InstallESD.dmg sha-1:

    2c8901209c5ce99bffcc035804cbdd13135bb930

InstallESD.dmg sha-256:

    0855931944b16a72ff18e057ffd5f5271aa0906d5ae427886a89c3a46ae8d122

Downloaded from MAS for MacBook Pro (Retina, 15-inch, Mid 2014) today. Thank you!

**Comment by drduh** [comment]
Those are the right hashes for the latest Sierra MAS download, but `SystemVersion.plist` (inside `BaseSystem.dmg`, which is inside `InstallESD.dmg`) reports build 16B2659. How are you determining it's build 16B2655?

**Comment by hellomaya** [comment]
I had same issue, and in the info.plist, it said it's 16B2658, I just downloaded it from app store, wasn't on the https://github.com/drduh/macOS-Security-and-Privacy-Guide/blob/master/InstallESD_Hashes.csv 

Same as above:

``
0855931944b16a72ff18e057ffd5f5271aa0906d5ae427886a89c3a46ae8d122
``

yet.

**Comment by drduh** [comment]
Replaced by 10.2.2 release: https://github.com/drduh/macOS-Security-and-Privacy-Guide/pull/186
