### ISSUE TITLE
Chrome alternatives

### ISSUE THREAD

**Issue by Eitot** [drduh/macOS-Security-and-Privacy-Guide#185]
There are some alternatives for Chrome that might be worth mentioning. The Chrome source code – Chromium – can be built manually and there are projects that distribute such Chromium builds. For instance: http://www.freesmug.org/chromium. There are also projects that remove the Google-specific parts for more privacy, such as https://github.com/Eloston/ungoogled-chromium.

**Comment by Eitot** [comment]
Never mind, I see that you specifically warn against them, though these two examples are maintained and current.

**Comment by reclaimer** [comment]
I'm using Ungoogled Chromium, replacing a standard Chromium build. It's nice(r), I no longer have to tell Little Snitch to block every Google. That means you can actually use Google stuff without also installing Chrome.

But I wouldn't recommend Ung-Chr yet. They are lagging behind 2 full releases (I think?). I'm hoping they can pull this off, though :)

**Comment by Eitot** [comment]
@reclaimer: They did fall behind for a couple of months, but are back on track now.
