### ISSUE TITLE
Document how to disable Apple trustd / symantec backdoor?

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [drduh/macOS-Security-and-Privacy-Guide#191]
/usr/libexec/trustd appears to be some sort of Apple-approved Symantec backdoor. Please advise more information on this and how to disable it / any side-effects?

**Comment by 9Yg1rxeSeha90ZU1** [comment]
It was noticed that trustd was communicating to symcd.com, a Symantec server.

**Comment by Eitot** [comment]
trustd is the process that validates certificates. Symantec is one of the certificate authorities whose root certificates Apple ships in macOS.
