### ISSUE TITLE
coming out of hibernation, login screen super slow after December update

### ISSUE THREAD

**Issue by kristovatlas** [drduh/macOS-Security-and-Privacy-Guide#192]
One of my MacOS machines is very slow at the login screen with the `destroyfvkeyonstandby` setting. It's so slow that some of the keystrokes are not registered when I enter my user password to unlock the machine. Once I get to the second login screen to actually log into my account, this effect goes away. It's particularly annoying for anyone with a password longer than the width of the password field, since at that point you can no longer see whether keystrokes are registered.

I know this isn't Apple bug tracking or support, but figured this might be a good place to find out if other users of this unusual setting are seeing similar behavior.

**Comment by burguesia** [comment]
I had a similar problem - during the first login i have to wait a few seconds before typing the password to be sure all characters were registered. Anyhow it just lagged at the beginning, if I waited 3/5 seconds then it went smooth.

Never really solved that issue - anyhow its been a while i've not been using `destroyfvkeyonstandby`. When I upgraded my internal SSD it stopped working, see [https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/124#issuecomment-253451827](url)

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Can confirm this issue too, but has been going since at least a year. Never resolved it.

**Comment by rawtaz** [comment]
Has it been reported to Apple?

22 dec 2016 kl. 12:41 skrev 9Yg1rxeSeha90ZU1 <notifications@github.com>:

**Comment by 9Yg1rxeSeha90ZU1** [comment]
unsure if ever reported since it only occurs with high security settings. they cant even properly fix GOTO FAIL or the numerous GNU softare flaws, how will they fix this

**Comment by drduh** [comment]
The described behavior is a bug and should be reported to Apple. I'm glad to accept a pull request explaining the nuance.
