### ISSUE TITLE
Captive Portal and mDNSResponder plist file locations

### ISSUE THREAD

**Issue by rawtaz** [drduh/macOS-Security-and-Privacy-Guide#194]
It looks like these commands in the guide reference files that does not exist in macOS 10.12.2:

~~~
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool YES
~~~

For the former (Captive Portal) I can't seem to find a file with "captive" in the name on a fresh install of 10.12.2, but it seems the latter have moved to either of the following:

~~~
/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
/System/Library/Preferences/Logging/Subsystems/com.apple.mDNSResponder.plist
~~~

**Comment by marcus-cr** [comment]
Still looking into this, but there is now a process running called `captiveagent`. Unsure if related to Captive Control.

**Comment by marcus-cr** [comment]
There _is_ a `captiveagent` process that is running, but unsure if it is related. Still investigating.

**Comment by drduh** [comment]
I'm pretty sure those files won't exist until the defaults values are written to them. Is there an error when you try to run those commands? With the captive control value set, `captiveagent` does not appear in the process table for me.

**Comment by rawtaz** [comment]
Yes, there was an error, basically saying "hey, the referenced file doesn't exist". I don't have it right here right now though, can get it if needed. But yes, the commands were unsuccessful, that's how I noticed this in the first place.

**Comment by marcus-cr** [comment]
@rawtaz @drduh I didn't receive any errors with `sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false` while running as a privileged user in terminal. The `captiveagent` process still runs. Forgotten I had reinstalled macOS on a reformatted drive.

**Comment by rawtaz** [comment]
@marcus-cr I did it on a fresh install of 10.12.2, did you do the same?

**Comment by marcus-cr** [comment]
Erased HDD and installed Mavericks with Internet Recovery (don't ask why), then installed 10.12.2.

**Comment by marcus-cr** [comment]
Long story short, yes @rawtaz

**Comment by marcus-cr** [comment]
@rawtaz Yes, no errors with fresh install or upgrade.

**Comment by marcus-cr** [comment]
@rawtaz Yes, no errors with fresh install of 10.12.2 nor upgrade.

**Comment by marcus-cr** [comment]
@rawtaz Does the error you receive state something along the lines of `Could not write domain /Library/Preferences/SystemConfiguration/com.apple.captive.control; exiting`?

**Comment by rawtaz** [comment]
@marcus-cr Tried both of these commands again, and I'm no longer getting an error when I run them. I'm not sure why, because I'm really certain I did get an error last time. However, I'm unable to find the command in the history.

I am beginning to suspect that I used the `read` argument instead of `write`, but I can't say. It's just likely, given the information you provided and the fact that it works when I run it now. At the same time I believe I did copy paste the commands I actually ran, when creating this ticket, so.. Who knows.

The error message you gave, it looks familiar - how did you come up with it? Skipping the `.plist` part in the command I presume?

Anyway; I have checked a newly upgraded system (10.12.2 from 10.9.x) and neither of the two files in question exists by default. Good to know.

**Comment by marcus-cr** [comment]
Glad it worked now. I got that error while omitting `sudo` and/or executing as non-admin account. 

I'll try once more to replicate this issue, unsure if I had to re-enter the command a second time either. Will confirm this later within a VM.

**Comment by marcus-cr** [comment]
Lessons to be learned here: don't enter commands in a hurry (especially while debugging/troubleshooting), and don't work on projects late while sleep deprived. @drduh this issue should be closed.

**Comment by rawtaz** [comment]
To be fair, this issue was about "hey, these files don't exist by default, is that expected?" than any commands not "working", so I'd say any sidestepping is excused :-)

In summary it's not unexpected that those two files do not exist, as it seems that when the commands have been run and created these files with settings in them, and the appropriate kicking of processes/reboot has been done, the result is as expected.

I agree the issue can be closed.
