### ISSUE TITLE
Reset FileVault 2 pmset Settings

### ISSUE THREAD

**Issue by Mattel88** [drduh/macOS-Security-and-Privacy-Guide#196]
I would like to know what I should do to restore all the default settings on my Macbook Pro to factory defaults. I was using these values:

$ sudo pmset -a powernap 0
$ sudo pmset -a standby 0
$ sudo pmset -a standbydelay 0
$ sudo pmset -a autopoweroff 0

$ sudo pmset -a destroyfvkeyonstandby 1
$ sudo pmset -a hibernatemode 25

Thanks in advance

**Comment by Eitot** [comment]
Check `man pmset`. Powernap, standby and autopoweroff are all enabled on supported machines, destroyfvkeyonstandby is turned off and hibernatemode should be 3 for portables.

I don’t know the standby delay though.

**Comment by Mattel88** [comment]
Nothing more? What happens if I go to energy saving options and chose "default" same result?

BTW: Would PRAM or SMCreset help?

**Comment by Eitot** [comment]
I don’t know what happens exactly, just test it. I doubt that PRAM or SMC have any effect on your energy preferences.

**Comment by drduh** [comment]
At this point, I have certainly lost track of the default pmset settings. If you find them out, please submit a PR for rolling back the suggested tweaks. Thanks!
