### ISSUE TITLE
Enhancement for Login/sudo

### ISSUE THREAD

**Issue by sogseal** [drduh/macOS-Security-and-Privacy-Guide#199]
Greetings all,
Thanks for everyone for this guide! I looked through the guide and noticed few things about yubikey. I also use my yubikey to login to my mac, im using /etc/pam.d/authorization for login and /etc/pam.d/sudo for executing sudo, requires your yubikey. Hopefully this is helpful...

**Comment by drduh** [comment]
I will gladly accept a pull request for hardening authorization actions with a hardware token. I haven't had a chance to use my Yubikey in this way yet, but I'm intrigued.
