### ISSUE TITLE
alf configuration

### ISSUE THREAD

**Issue by Hungry4Sec** [drduh/macOS-Security-and-Privacy-Guide#202]
Hey all,

Sorry bit of a complete newb here, so this might be common knowledge but when configuring the main apple firewall my system has a com.apple.alf.pllist in the /usr/libexec/ApplicationFirewall folder. It does some interesting things like permanently allow netbios, etc. Was wondering if someone with more experience can take a look at this, and let us know if this is known/approrpiate or something that should be configured in addition to the wonderful guide already posted.

Thanks again for all of your guys' time and effort.

**Comment by drduh** [comment]
Not sure about this. Resolving.
