### ISSUE TITLE
Physical Access > Blocking ports mitigations

### ISSUE THREAD

**Issue by eliotsykes** [drduh/macOS-Security-and-Privacy-Guide#204]
Apparently some organizations use superglue or purchase port blockers to hinder an attacker accessing hardware ports.

Would a couple sentences on this be a welcome addition to the Physical Access section? (Though I don't feel qualified to write them).

https://github.com/drduh/macOS-Security-and-Privacy-Guide#physical-access

**Comment by eliotsykes** [comment]
Similarly I've heard of tamper-evident tape/stickers to reveal when a device has been interfered with.

**Comment by drduh** [comment]
Like this? https://twitter.com/topherolson/status/745294977064828929

I'd be curious if tape over a microphone is effectual. Tape over webcam is banally obvious to privacy-conscious folks. Epoxy in other peripheral ports seems insane; just have good physical control of your machine.

**Comment by TraderStf** [comment]
For the micro, put an 'empty' plug, no cable and set it as input.
It does not cover all the possibilities though, hack to use internal.

For ports, I saw plugs with a locker are available, reliable.

[plugShield](http://appshopper.com/mac/business/plugshield) can block ports, if you trust it or don't kill it.

> While activated, plugSHIELD will shut down any plug & mount attempts from USB, firewire, memory card and other ports. Your mac will refuse to accept portable devices plugged into it, be it a USB flash drive, an SD card, or a firewire removable hard disk.

**Comment by TraderStf** [comment]
Another one for mic
http://appshopper.com/mac/productivity/push-mic-control
