### ISSUE TITLE
Command to install dnsmasq need to be updated for new os x version

### ISSUE THREAD

**Issue by lebensterben** [drduh/macOS-Security-and-Privacy-Guide#212]
In the new os x the dnsmasq config file is no longer under ~/homebrew/opt/dnsmasq/

So the correct command should be

sudo cp /usr/local/opt/dnsmasq/dnsmasq.conf.example /usr/local/etc/dnsmasq.conf

**Comment by drduh** [comment]
Is this correct? Even if Homebrew is installed to `~/homebrew`?

**Comment by lebensterben** [comment]
On the official website of homebrew it says:

Homebrew installs packages to their own directory and then symlinks their files into /usr/local.

So I think using /usr/local shall always be the best solution.

**Comment by gvarisco** [comment]
@drduh hi! What @lebensterben says is correct. I'd stick to what homebrew's official doc says.

**Comment by drduh** [comment]
Thank you.
