### ISSUE TITLE
backups: discussion of time machine backup to encrypted volume

### ISSUE THREAD

**Issue by mahiki** [drduh/macOS-Security-and-Privacy-Guide#215]
The recommended backup solution (encrypt with `gpg` and copy to external volume) is a wide divergence from standard practice which is time machine incremental backups to an encrypted volume. This deserves some discussion, at least some bullet points on why the current default is insufficient.

- [related to issue #53](https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/53)
- The current doc recommends SpiderOak, Arq, Espionage, and restic, no rationale is provided for trusting these ahead of time machine/external drive backups.
- would rsync of time machine encrypted volume to cloud volume qualify as encrypting before storing, or is there a vulnerability between the OS and the usb connected external drive that is a concern?

**Comment by kun-zhou** [comment]
It seems like the backup strategies discussed in the guide is mainly backup of individual directories rather than the entire system, which is what Time Machine does. I think backing the entire system with time machine on an encrypted HFS+ FS is secure enough.

**Comment by rawtaz** [comment]
One should have at least two different backup systems in place, to different media, onsite and offsite or two different "offsites".

I use TM and restic for this, as per above, it works great and I know that if one of them fail there's little risk that the other does as well at the same time.


19 apr 2017 kl. 17:00 skrev kun-zhou <notifications@github.com>:

**Comment by drduh** [comment]
The backup section could use improvement and more diverse strategies. Please send PRs.
