### ISSUE TITLE
Discussion: macOS Sierra's native "pam_smartcard.so" PAM module

### ISSUE THREAD

**Issue by kun-zhou** [drduh/macOS-Security-and-Privacy-Guide#217]
My Issue
--------
My goal is to **properly** use macOS Sierra's native "pam_smartcard.so" PAM module in place of/ in conjunction with traditional user password. The most imminent problem I am facing now is the occasional prompts for keychain password and I was hoping people who are interested in it can help out a bit. Please allow me to elaborate a bit.

Intro
-------
Recently I obtained a Yubikey 4 to use as PIV smart card to login to my macOS. I was able to set it up using Yubikey's PIV manager quite easily. The yubikey can be used to login when you first startup your computer or when you log back in from screensaver or after wake from sleep. Moreover, upon login, inserting the key should automatically detect the user account associated with the key and prompt you for the PIN of the smartkey.

Probing the `/etc/pam.d`, we can see two files `authentication_ctk` and `screensaver_ctk`, each with `auth       required       pam_smartcard.so 		use_first_pass ` as the first uncommented line. Learning from these two files, I quickly added the line `auth       sufficent      pam_smartcard.so ` (without the option `use_first_pass`)  to the `sudo` file and was able to use my Yubikey as a PIV smartcard to gain `sudo` privilege. 

Now, when I use System Preferences to change my settings, I often have click the little lock on the bottom left corner of the window and enter my password. macOS does not seem to let you use the password directly, so I added `auth      sufficient       pam_smartcard.so 		use_first_pass ` as the first uncommented line in `authentication` in the `pam.d` directory, and now I am able to use my PIV key to authenticate in these GUI prompts as well.

Some thoughts
---------------
1. Upon login, macOS will "sniff" if there is a smart card inserted, if there is, it authenticates with the module `authentication_ctk`,  and if not, it authenticates with ``authentication`. Same goes for screensaver. This is deduced from the string `builtin:smartcard-sniffer,privileged` from `/System/Library/Security/authorization.plist`.

2. There are other ways to log into mac if one wants to use a yubikey, check out `https://github.com/Yubico/pam-u2f` and `https://github.com/Yubico/yubico-pam`. These are all PAM modules as you can see. (for `pam-u2f` to work on mac, read issue 39 on the github page for a good resolution.)  My problems with these two options are that they do not require user to enter the PIN for the Yubikey. Unless you set them as one of the required auth in the PAM config files (use together with password), it would mean whoever has your yubikey will have access to your computer without the password. And the smart card way requires a relatively short PIN, so it is easier to use if you have long password like me and do not want to enter it enter time you authenticate.

Keychain
---------
I didn't mention that both `pam-u2f` and `yubico-pam` does not seem to support Keychain unlocking but Sierra's native PAM module `pam_smartcard.so` does (also a good reason to use smart card to authenticate). If you log in with `pam_smartcard.so`, macOS will automatically unlock the login keychain for you. (This happens under the hood if you just use your regular password to authenticate) 

Now, Apple seems to "force" you to have a consistent password among FileVault2, user password, and login keychain password. If you have FV enabled, when you enter your password when you boot up, macOS will pass-through your FV password to the login window, and then login window will passthrough your password to Keychain to unlock the login keychain, which is required by your calendar, iCloud (if you use it), mail account, chrome, etc. It is actually possible to have three different passwords for these three services, but then you will have to enter them three times.

You can disable passthrough of FV password to user authentication by using `defaults write /Library/Preferences/com.apple.loginwindow DisableFDEAutoLogin -bool YES`, so that you can use your yubikey for authentication.

__Caveat with Keychain__

With smart card login, some times the Keychain is not unlocked automatically and prompts for password. (while other times it works perfectly) What I have tried:

1. Log in to my account  _*without*_  needing manual unlock for keychain.
2. Enter screensaver mode.
3. Insert yubikey and enter the PIN on wake up.
4. Log in without needing manual unlocking.

Another thing I tried:
1. Log in to my account _*with*_ needing manual unlock for keychain.
2. Refuse to manual unlock by hitting cancel in the keychain password prompt.
3. Enter screensaver mode.
3. Insert yubikey and enter the PIN on wake up.
4. A Keychain manual unlock prompt come up again.
5. If I enter the password for the keychain, the issue goes away for some time, but comes back periodically.

References
--------
1. https://blog.trezor.io/trezor-u2f-login-into-your-mac-os-x-9fdd808b0aa4 (This configures U2F instead of the smart card I am trying to achieve here, but I borrowed some insights on the `pam.d` directory)
2. https://ludovicrousseau.blogspot.com/2016/12/macos-sierra-and-pamsmartcard.html (Nice reference to man pages)
3. http://www.richard-purves.com/?s=smart+cards (He has a set of pretty neat slides, but hard to understand for me at least)
4. https://opensource.apple.com/source/pam_modules/pam_modules-159/modules/pam_smartcard/ (Source for the `pam_smartcard` module, again, too hard for me)
5. https://github.com/franton/Create-FV2-Only-User

**Comment by franton** [comment]
Ha! Nice to see my work referenced elsewhere. I'm working on this myself right now.

**Comment by gregbkr** [comment]
Hello @drduh @franton : we are facing the exact same issue while try to install yubi + mac logon. Keychain still prompt for password :-/ Did you find any fix / workaround?
Thank you for your answer!

**Comment by trubalcain** [comment]
For the keychain problem try the following:

Disable loginwindow keychain update per user
-----------------------------------------------------------------------------
To disable:
defaults write com.apple.keychainaccess SyncLoginPassword -bool false

To enable:
defaults write com.apple.keychainaccess SyncLoginPassword -bool true

This is a per-user setting and is stored in/Users/username/Library/Preferences/com.apple.keychainaccess.plist

**Comment by drduh** [comment]
Please send a PR - even if you don't have it working 100%, it would be good to have in the guide.
