### ISSUE TITLE
Question: How to prevent applications to access my screen contents and clipboard?

### ISSUE THREAD

**Issue by kun-zhou** [drduh/macOS-Security-and-Privacy-Guide#218]
I have Yubikey Authenticator installed on my Mac. The software is able to read QR code from the screen without any warning. Does it mean any other softwares, possibly malicious, can also read my screen contents? If so, is there any way to stop it?

Another issue is with regard to clipboard. Is it possible to restrict applications access to the clipboard (especially the paste command) on apple laptops (only allow `Ctrl + V` to paste)? I realize that with apple's new universal clipboard, this will be somewhat complicated.

**Comment by drduh** [comment]
I'm not aware of ways to mitigate either risk. I'll keep your request open for a little while to brainstorm ideas by others. But really, both behaviors are features, not bugs, of the OS.

**Comment by TraderStf** [comment]
There is a small tool that empty the clipboard after x seconds, will try to find it back.
Can use this site... far better than aPE store... http://appshopper.com

**Comment by victorberland** [comment]
If you're really paranoid about it, you could probably try to compartmentalise in VMs as much as possible (Similarly to how Qubes does it). That way, you could have a really secure main OS with as much tech and blocking as possible and have individual VMs for "untrusted" apps and important ones like the YubiKey Authenticator or your passwd manager.

**Comment by kxpvcr** [comment]
@TraderStf Possibly [Cleanboard](http://appshopper.com/mac/utilities/cleanboard)? It's also available on the macOS App Store (with the added benefit of sandboxing, right?).

**Comment by TraderStf** [comment]
@kxpvcr seems so
