### ISSUE TITLE
How can you reccomend Google Chrome with all of the tracking that it actively does PLUS how it is not open-source?

### ISSUE THREAD

**Issue by Masterofsquid** [drduh/macOS-Security-and-Privacy-Guide#225]
I can't grasp how Google Chrome would help anyone's privacy or anonymity. `

**Comment by drduh** [comment]
I understand the concern and criticism.

The reason for the recommendation is simply, that's my personal choice and recommendation as a security professional and Mac user. I base my recommendation off the consensus of other security professionals who extol the code quality and features of Chrome, for example robust sandboxing, and my own experience.. Chrome also has a very capable security staff; their vulnerability rewards program is more popular than other browsers and is quite effective. This is not to say Firefox has poor security, nor that it's even inferior (in fact, the guide points to Firefox as "an excellent browser"), just that Chrome's security is actually good.

With regards to privacy, I would like to turn your attention to Chrome's [Privacy Whitepaper](https://www.google.com/chrome/browser/privacy/whitepaper.html). It appears to explain how most (all?) privacy features (or anti-features) function and what steps one can take to effectively opt-out of them. And while Chrome is closed-source, so is the entire operating system, and most of the other software on it, thus I don't think it's a relevant characterization.

You (and others) are certainly welcome to disagree and I appreciate you voicing the opinion. If you can reasonably articulate reasons not to use Chrome, or reasons to use an alternative browser, I will review your pull request and welcome improvements to the guide. Thank you.
