### ISSUE TITLE
Add a note to firmware password for non-qwerty users

### ISSUE THREAD

**Issue by mercieralex** [drduh/macOS-Security-and-Privacy-Guide#231]
I followed the guide to add a firmware password to my MacBook Pro and I almost add a heart attack when the "wrong password" notification came up.

The source of the problem was that when setting the firmware password, my MacBook Pro was in US qwerty mode while when asked for it, the FR azerty mode was on (that is a weird design in my opinion).

I believe this could be an issue for a lot of non qwerty users. Would a note on this issue be a welcome addition to the Firmware section?

https://github.com/drduh/macOS-Security-and-Privacy-Guide#firmware

**Comment by omesrome1** [comment]
hello motherfacker

**Comment by drduh** [comment]
Please send a PR with the same.
