### ISSUE TITLE
Firewall IP and proxy.pac blocks ; Hosts lists ; Recommend privatizing proxy on localhost to block tracking, malware, ads

### ISSUE THREAD

**Issue by essandess** [drduh/macOS-Security-and-Privacy-Guide#234]
This is a nicely written and comprehensive guide—thanks.

A few comments:

* **IP Blocks.** [dshield.org](https://secure.dshield.org/)'s IP lists can be used for kernel-level IP blocks with `pf`. These configuration files, [pf.conf](../../../../essandess/osxfortress/blob/master/pf.conf) and [blockips.conf](../../../../essandess/osxfortress/blob/master/blockips.conf), along with the plists [net.dshield.block.plist](../../../../essandess/osxfortress/blob/master/net.dshield.block.plist) and [net.emergingthreats.blockips.plist](../../../../essandess/osxfortress/blob/master/net.emergingthreats.blockips.plist) accomplish this with regular IP block updates.

* **Hosts.** The lists in the [hosts file](../../macOS-Security-and-Privacy-Guide#hosts-file) section here are all relatively limited. I recommend using the [hpHosts](https://www.hosts-file.net/) host file with a front-end privatizing proxy. This [repo](../../../../essandess/osxfortress) does this along with a `launchd` plist [net.hphosts.hosts.plist](../../../../essandess/osxfortress/blob/master/net.hphosts.hosts.plist) for regular updates of the hosts file.

* **Tracking, Malware, and Ad Blocks.** I recommend the use of a localhost (or LAN) proxy to block tracking, malware, and advertising sites, as described in the [osxfortress](../../../../essandess/osxfortress) repo. If used in conjunction with an [osx-openvpn-server](../../../../essandess/osx-openvpn-server), these protections extend to every device that uses the VPN server. A proxy chain using `squid` and `privoxy` are used to create a highly performant and effective privatizing proxy.

* **Proxy.pac blocks**. Configure the network to use a filtering [proxy.pac](../../../../essandess/easylist-pac-privoxy/blob/master/proxy.pac) file for tracker, ad, and malware blocking. The repo [easylist-pac-privoxy](https://github.com/essandess/easylist-pac-privoxy) does this by converting EasyList rules to a proxy.pac file, along with [Privoxy configuration files](../../../../essandess/adblock2privoxy).

* **SSH hardening**. Not that ssh attack scripts are an actual threat if you've turned off password authentication, but I have observed with both snort and system logs that hardening the ssh configuration drops ssh attack attempts to almost zero. On macOS Sierra:

Generating ssh keys:

```
ssh-keygen -t ed25519 -o -a 100
ssh-keygen -t rsa -b 4096 -o -a 100
```

`diff /etc/ssh/sshd_config /etc/ssh/sshd_config.orig`
```
18,19d17
< KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
< 
28,29d25
< Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
< 
63d58
< PasswordAuthentication no
68d62
< ChallengeResponseAuthentication no
129,130d122
< 
< MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
```

`diff /etc/ssh/ssh_config /etc/ssh/ssh_config.orig`
```
20,30d19
< Host *
<         SendEnv LANG LC_*
< 
<         KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
<         PasswordAuthentication no
<         ChallengeResponseAuthentication no
<         PubkeyAuthentication yes
<         HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
<         Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
<         MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
```

**Comment by drduh** [comment]
Please send these and any other recommendations you may have as separate pull requests.
