### ISSUE TITLE
`codesign -dvv` doesn't verify signature

### ISSUE THREAD

**Issue by l2dy** [drduh/macOS-Security-and-Privacy-Guide#235]
`codesign -d` only displays information and doesn't verify the signature, more `-v`s would only increase verbosity.

`spctl -a -v` or `pkgutil --check-signature` should be used instead.

**Comment by l2dy** [comment]
`codesign -vv` following `codesign -dvv` works but not in a single command.

**Comment by drduh** [comment]
Very nice catch, thanks.
