### ISSUE TITLE
Update Little Snitch instructions for version 4

### ISSUE THREAD

**Issue by drduh** [drduh/macOS-Security-and-Privacy-Guide#240]
@obdev have kindly provided me a upgrade license to the latest version of Little Snitch. The UI has changed and there's new features worth explaining.

**Comment by VFS** [comment]
I think it would be useful to include instructions on how to use Little Snitch automatic profile switcher with a VPN (for example, having a default 'Untrusted Connection' profile set as 'Silent Mode - Deny Connections', that changes to a 'Trusted Connection' profile when connected to the VPN)

**Comment by drduh** [comment]
I'm just having trouble configuring the latest version of LS in vmware - the kernel extension won't load. If anyone else is a LS fan and would like to document it more thoroughly, please be my guest.

**Comment by blochberger** [comment]
Have you looked into the Gatekeeper settings (System Preferences → Security → General). In recent macOS you might need to explicitly allow kernel extensions to be loaded (see https://www.obdev.at/products/littlesnitch/high-sierra-notes.html).

**Comment by drduh** [comment]
That option doesn't appear for me in Preferences. I'll nuke the vm and try again to see if it'll show up.

**Comment by HazCod** [comment]
You do have to manually approve the Little Snitch kext once after installing.

**Comment by drduh** [comment]
I don't use it much now, maybe someone else can update it.
