### ISSUE TITLE
DNS guide has too many problems

### ISSUE THREAD

**Issue by benjaminshell** [drduh/macOS-Security-and-Privacy-Guide#248]
The cp command in the Dnsmasq instructions is unnecessary. The dnsmasq.conf file is already in /usr/local/etc/

**Comment by benjaminshell** [comment]
I'm trying to follow the DNS guide and there are numerous issues with it. One major flaw is that the instructions for Dnsmasq tell the user to set the DNS server to 127.0.0.1, and then tells the user to download the dnscrypt tool. At that point, there is no DNS service at 127.0.0.1 and connection to the internet is not possible.
The guide also points to the configuration file in the old file setup of homebrew. It should be /usr/local/Cellar/dnscrypt-proxy/1.9.5/homebrew.mxcl.dnscrypt-proxy.plist and not located in the home directory. The find command should be `find /usr/local -name homebrew.mxcl.dnscrypt-proxy.plist`

**Comment by lebensterben** [comment]
I've successfully implemented both dnsmasq and dnscrypt-proxy. And one must first install dnscrypt-proxy first, then dnsmasq as pointed out by @benjaminshell .

An update to this section is needed.

**Comment by sesam** [comment]
Do you have any comments on performance? Fast DNS is important, and
proactively resolving and logical chunking or grouping of host names could
increase the anonymity set. Maybe zero knowledge/SRP connections randomly
aimed at DNS aggregators. Anyone tried something like this? DNS zone TTL *2
or *8 should make this feasible, increasing both performance and privacy.
Dynamic dns hosts can be used for tracking, so a white/gray/blacklist would
be nice, but hard to create and update reliably. For blacklisting, maybe
just supply proof of URLs that add in dynamic domains to track you is
enough. For gray and blacklisted sites, access them through some mixing
proxies that render and forward as a VNC without mouse movement javascript
events. Without such countermeasures, is any DNS encryption worth it? Maybe
if combined with cert pinning. Also depends on adversary's profile.

**Comment by TraderStf** [comment]
@sesam may be I don't understand, but dnscrypt-proxy has white/black lists as ~extensions.

**Comment by TraderStf** [comment]
@sesam perhaps you are looking for this
https://github.com/pwnsdx/RandomDNS
