### ISSUE TITLE
Add to section on macOS activation and mention privacy implications

### ISSUE THREAD

**Issue by iosecure** [drduh/macOS-Security-and-Privacy-Guide#249]
Hey drduh,

Noticed the section on the appearance of activation on the TouchBar MBPs and thought you might be interested in either looking at or linking to this gist I wrote discussing the dangers posed by a potential iOS-ification of macOS, including the risks associated with activation.

https://gist.github.com/iosecure/357e724811fe04167332ef54e736670d

 

Activation on macOS is a symptom of the secure enclave (sepOS) on the TouchBar which itself runs a stripped down version of iOS and is or is going to be used (among other things) by Apple to enforce a  verified boot policy, meaning that in future disabling services and modifying system launch agents/daemons will likely become impossible unless Apple allows users to disable it in recovery as is the case with SIP. (Note that SIP does not prevent disabling system launch agents/daemons via recovery at the moment, which is the ONLY (except removing/renaming binaries) way to stop Apple's numerous surveillance services from loading).

This is really dangerous of Apple since it completely removes the ability to control what runs on YOUR device and will force you to run their highly intrusive binaries. If Apple actually cared about their users, they would allow them to override this, offer an option to create user self-signed verified boot keys and flash them manually in a revamped and hardened recovery OS. The issue here is about authentication. If the recovery OS were encrypted, and verified, and various sets of credentials could be configured for various levels of privilege in the recovery, then you could theoretically have secure boot that YOU controlled. When updating, the user would have to enter recovery and disable the verification and then flash a new set of keys after. Trammell Hudson's HeadsOS should have been used as inspiration, not Intel Boot Guard (see https://github.com/osresearch/heads).  Some might say that moving most of the root of trust to the user is risky, but a TPM which can have keys flashed to it in an authenticated (local, not online) manner is better than having no form of boot verification at all as is the case on older machines. After all, does Apple have some overlord which tells them what they are allowed to run on their development machines? No? So does that mean maybe Apple internally can do security just fine without having some third party controlling them? Well then, what about end users too? Saying that removing all freedom from a widely used OS is justifiable for security purposes is nonsense.  

Activation also allows Apple (and Akamai) to gather an enormous amount of sensitive metadata, and allows Apple (and those Apple cooperates with) to link a device's UUID to your real identity and associated identifiers.

Sorry if this was messy, but I didn't have much time.

**Comment by drduh** [comment]
These are significant findings definitely worth talking about in the guide, as well as hardware/firmware security and hardening (or lack of ability to thereof) more generally.

Is that gist the final published version of your analysis? I would really like a condensed form of it to appear at the top of the guide, with a link to the rest in detail.

**Comment by drduh** [comment]
[Push Away Your Privacy: Precise User Tracking Based on TLS Client Certificate Authentication](http://tma.ifip.org/wordpress/wp-content/uploads/2017/06/tma2017_paper2.pdf) (pdf) perhaps a relevant work to your points.

**Comment by iosecure** [comment]
I will see if I can write a condensed version at some point in the future, but I cannot promise anything at this point I'm afraid.

While the article you linked on plaintext CCA is interesting, I don't really see it as relevant to the issue I am highlighting. Plaintext CCA is an issue that plagues many services, not just the push services that the author chose to focus on.

Plaintext CCA issues imho seem more like a design oversight, whereas what I'm trying to highlight is that Apple actively has built iOS in such a fashion that using it requires exchanging a large amount of information with them. It seems a bit strange to focus on CCA issues when APNS (and so many other services) itself uses the UUID of the device (which links directly to device purchase data) to authenticate for push services with Apple. 

Beyond that there are many other data confidentiality issues with APNS and any individual or corporation that has no choice but to use iOS devices should disable all notifications since Apple does not let you discern between local and remote notifications. The only realistic way to deal with this is to block access to Apple's servers at the network level and force traffic through a VPN (however, Apple's VPN APIs do not send all network traffic via the VPN, some Apple process traffic will avoid the VPN, which obviously creates issues when using the cellular interface).


The point is Apple is making macOS more like iOS, removing independent end-user configurability, introducing more and more services that send lots of data to them, preventing you from even using the device before you let the device send real identity-linked data to them, and just calling it "security". It is perfectly possible to have just as secure or even more secure devices without having to interact with Apple all the time. I would suggest that it seems suspicious that this is occurring. Some of the links posted in this repo already show how sysadmins in companies trying to maintain independent, secure configurable images for large fleets of devices are concerned by this issue as well. I had a link to a blog post by a sysadmin about this issue at some point, but I can't seem to find it right now.

**Comment by iosecure** [comment]
I have added a somewhat condensed update to the bottom of the gist (https://gist.github.com/iosecure/357e724811fe04167332ef54e736670d) with a TL;DR. Maybe the updated TL;DR is sufficient to place in the guide with a link. Otherwise, if you don't think it is too long, the condensed version below the TL;DR could be used.

**Comment by drduh** [comment]
Thanks, @iosecure. That is very valuable work.
