### ISSUE TITLE
Create section on sensitive metadata collected and stored on filesystem

### ISSUE THREAD

**Issue by iosecure** [drduh/macOS-Security-and-Privacy-Guide#250]
Hi drduh,

I also wanted to share some areas on metadata stored on Macintosh HD that could be mentioned in the guide.

After disabling agents/daemons/processes you don't like that won't break the core OS (only way to keep up to date on this is get a list from launchd, test disabling individually in recovery), METADATA STORED on the filesystem might be of interest.

Here are some areas that are probably of interest. (USER/ROOT in brackets in titles indicate whether you require root to execute commands)

Note, that it is highly recommended checking all files yourself in 

~/Library/Preferences/, 
~/Library/Containers/<APP>/Data/Library/Preferences 
/Library/Preferences

for metadata since it can differ in amount from user to user (USE PREF SETTER OR SIMILAR 
TOOLS IF YOU WANT A GUI)

Sidebar Volume List Preference File (USER)

	~/Library/Preferences/com.apple.sidebarlists.plist

	Contains historical list of volumes attached.

	Clear command:

	/usr/libexec/PlistBuddy -c "delete :systemitems:VolumesList" ~/Library/
	Preferences/com.apple.sidebarlists.plist

	Add a User Agent with launchd or LaunchControl (www.soma-zone.com)
	to run this command in a shebanged, chmod'd and chown'd script in a location of 
	your choice as repeated as often as you choose with StartInterval

Bluetooth Metadata (ROOT)

	/Library/Preferences/com.apple.Bluetooth.plist

	Contains device history, etc.  (WARNING, CAN CAUSE ISSUES)

	If you don't use Bluetooth, clear this, otherwise
	no that doing this will break bluetooth and require you to 
	repair your devices. Still suggest checking the contents of the preferences file;
	with some modification, the commands could remove all devices except
	ones you need to use.

	defaults delete /Library/Preferences/com.apple.Bluetooth.plist DeviceCache
	defaults delete /Library/Preferences/com.apple.Bluetooth.plist IDSPairedDevices
	defaults delete /Library/Preferences/com.apple.Bluetooth.plist PANDevices
	defaults delete /Library/Preferences/com.apple.Bluetooth.plist PANInterfaces
	defaults delete /Library/Preferences/com.apple.Bluetooth.plist SCOAudioDevices

Printer Job Cache (CUPS) (ROOT)

	/var/spool/cups

	Print job history, etc. Check directories before running commands

	
	rm -rfv /var/spool/cups/c0*
	rm -rfv /var/spool/cups/tmp/*
	rm -rfv /var/spool/cups/cache/job.cache*

iOS devices connected (ROOT)

	Clear history of iOS devices attached in preference files
	

	

	defaults delete /Users/<USER>/Library/Preferences/com.apple.iPod.plist "conn:128:Last Connect"
	defaults delete /Users/<USER>/Library/Preferences/com.apple.iPod.plist Devices 
	defaults delete /Library/Preferences/com.apple.iPod.plist "conn:128:Last Connect"
	defaults delete /Library/Preferences/com.apple.iPod.plist Devices
	rm -rfv /var/db/lockdown/*

QuickLook Thumbnail Data (USER+ROOT)

	QUICKLOOK THUMBNAIL DATA IS STORED FOR BOTH ROOT AND REGULAR USER (501)

	It is possible to clear using "qlmanage -r cache" command, but this
	writes to the file "resetreason" in the quicklook directories, and
	states that the quicklook cache was manually cleared. Best to 
	simply clear the cache this way. To be certain, executing
	the below commands after executing the qlmanage command
	is recommended

	Get User (501) and Root (000) DARWIN_USER_CACHE_DIR values to find current cache dir in /private/var/folders/...
	NOTE, CHECKING CONTENTS OF OLD DIRECTORIES IS HIGHLY RECOMMENDED AS WELL, JUST BE CAREFUL - SEE WHAT USER
	THE DIRECTORIES BELONG TO

	(USER - 501)

	getconf DARWIN_USER_CACHE_DIR

	(ROOT - 000)

	getconf DARWIN_USER_CACHE_DIR

	ROOT

	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/exclusive 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite-shm 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite-wal 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/resetreason 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/thumbnails.data 
	 rm -rfv </PATH/TO/USER-501/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/thumbnails.fraghandler 
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/exclusive 
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite 
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite-shm
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/index.sqlite-wal
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/resetreason
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/thumbnails.data
	 rm -rfv </PATH/TO/ROOT-000/CACHE/DIR>/com.apple.QuickLook.thumbnailcache/thumbnails.fraghandler

Finder Preference File (USER)

	
	

FINDER PREFERENCE FILE CONTAINS HIGHLY SENSITIVE METADATA COLLECTED ON FILE OPERATIONS, SEARCHES, ETC

	Command to clear:

	defaults delete ~/Library/Preferences/com.apple.finder.plist FXDesktopVolumePositions
	defaults delete ~/Library/Preferences/com.apple.finder.plist FXRecentFolders
	defaults delete ~/Library/Preferences/com.apple.finder.plist RecentMoveAndCopyDestinations
	defaults delete ~/Library/Preferences/com.apple.finder.plist RecentSearches
	defaults delete ~/Library/Preferences/com.apple.finder.plist SGTRecentFileSearches

/var/db files (ROOT)

/var/db/systemstats/
/var/db/uuidtext/
/var/db/diagnostics/
/var/log/DiagnosticMessages/

	CLEARING THESE DIRECTORIES AND/OR LOCKING THEM CAN BREAK LOGGING, BUT
	DOES NOT CAUSE ANY OTHER ISSUES, SO IF YOU DONT WANT METADATA LYING AROUND

	YOU CAN CLEAR (rm -rfv <dir>/*) CHMOD (chmod -R 000 <dir>) and lock (chflags -R uchg <dir>) these directories

/var/db/CoreDuet/* (ROOT)

	CHECK /VAR RECURSIVELY YOURSELF AS WELL FOR POTENTIALLY SENSITIVE DATA...

	THIS CAN BREAK SOME LOGGING ON THE MACHINE, SO IF YOU WANT TO RETAIN IT, DONT 
        EXECUTE IT UNLESS
	YOU NEED TO. DOESNT AFFECT STABILITY...

	rm -rfv /var/db/CoreDuet/*

/VAR/ FILES (ROOT)

	NOTE, THIS IS ONLY IF YOU WANT TO CLEAR ALL LOGS ON THE SYSTEM, HAVING LOGS CAN 
        BE USEFUL
	BUT IF YOU WANT TO CLEAR, HERE'S HOW

	# CLEAR:
	#
	# SYSTEM.LOG AND ASSOCIATED BACKUPS
	# WIFI.LOG AND ASSOICATED BACKUPS
	# ASL LOGS
	# POWERMANAGEMENT LOGS
	# SYSTEMSTATS LOGS (DAILY/WEEKLY/MONTHLY.OUT)
	# CUPS LOGS
	# AUDIT LOGS

	rm -rfv /var/log/system.log
	rm -rfv /var/log/system.log.*.gz
	rm -rfv /var/log/wifi.log
	rm -rfv /var/log/wifi.log.*.bz2
	rm -rfv /var/log/asl/*
	rm -rfv /var/log/powermanagement/*
	rm -rfv /var/log/daily.out
	rm -rfv /var/log/weekly.out
	rm -rfv /var/log/monthly.out
	rm -rfv /var/log/cups/*

	#auditlog clearing clears all created (i.e. not currently running logs) using 20*.20* to designate all log files started in year 20XX and having terminated in the year 20XX (hence 20*.20*)
	
	rm -rfv /var/audit/20*.20*
	rm -rfv /var/audit/20*.crash_recovery

CLEAR WIFI AP DATA ON NVRAM (ROOT)

	macOS writes preferred wifi AP data (including credentials) to nvram
	You can prevent this with Little Flocker as long as it still works on your OS version if you can 
        still access the installers

	Otherwise, you can clear the data manually using the nvram command

	Note, there is a chance that this will break in 10.13 since I recall hearing that 10.13 hardens
	nvram access, shame that Apple didn't preserve user access to override this, but in a secure 
        manner...

	nvram -d 36C28AB5-6566-4C50-9EBD-CBB920F83843:current-network
	nvram -d 36C28AB5-6566-4C50-9EBD-CBB920F83843:preferred-networks
	nvram -d 36C28AB5-6566-4C50-9EBD-CBB920F83843:preferred-count 
	
	

NSGlobalDomain Pref File (USER)

macOS stores list of names of all attached USB devices in NSGlobalDomain as well as list of recent finder searches and locations

	defaults delete -g SGTRecentFileSearches
	defaults delete -g NSNavRecentPlaces
	defaults delete -g "<ATTACHED DEVICE NAME HERE>"

	

macOS pseudo-keylogging (ROOT)

	

macOS collects sensitive information about what you type even if user dictionary and suggestions are off

	I suggest clearing, chmod 000 and locking with chflags recursively

	rm -rfv ~/Library/LanguageModeling/* ~/Library/Spelling/* ~/Library/Suggestions/*
	chmod -R 000 ~/Library/LanguageModeling ~/Library/Spelling ~/Library/Suggestions
	chflags -R uchg ~/Library/LanguageModeling ~/Library/Spelling ~/Library/Suggestions

QuickLook Application Support Metadata (ROOT)

	Clear and lock (contains cloudthumbnails.db)

	
	rm -rfv ~/Library/Application Support/Quick Look/*
	chmod -R 000 ~/Library/Application Support/Quick Look
	chflags -R uchg ~/Library/Application Support/Quick Look	
	

Root FS DocumentRevisions Directory Metadata (ROOT)

/.DocumentRevisions-V100 can contain a large amount of highly sensitive metadata
IF YOU USE APPLE'S VERSION HISTORY IN APPLE APPLICATIONS, THIS WILL BREAK THIS FUNCTIONALITY
	
	YOU COULD JUST DISABLE REVISIOND, BUT THIS CAN CAUSE OTHER ISSUES...

	To avoid doing that, 

	rm -rfv /.DocumentRevisions-V100/*
	chmod -R 000 /.DocumentRevisions-V100
	chflag -R uchg /.DocumentRevisions-V100

Saved Application State Data (ROOT)

Can contain sensitive info. NOTE BREAKS SAVED APPLICATION STATE (SESSION RESUMPTION), BUT IF YOU DONT WANT YOUR SESSION SAVED, THIS IS USEFUL

	rm -rfv  ~/Library/Saved Application State/*
	rm -rfv ~/Library/Containers/<APPNAME>/Saved Application State

	chmod -R 000 ~/Library/Saved Application State/
	chmod -R 000 ~/Library/Containers/<APPNAME>/Saved Application State
	chflags -R uchg ~/Library/Saved Application State/
	chflags -R uchg  ~/Library/Containers/<APPNAME>/Saved Application State

AutoSave Information (ROOT)

	Can also contain sensitive info

	~/Library/Containers/<APP>/Data/Library/Autosave Information
	~/Library/Autosave Information

	Clear, chmod 000 and lock as above

Siri Analytics Database (gets created even if Siri launchd agent disabled and disabling assistantd breaks the OS)

	~/Library/Assistant/SiriAnalytics.db

	Clear Directory, chmod 000 recursively and lock recursively as above

~/Library/Preferences/com.apple.iTunes.plist

	Recent Search Data (will need periodic clearing)

	defaults delete ~/Library/Preferences/com.apple.iTunes.plist recentSearches

	
	If you do not use Apple ID-linked services, otherwise may cause issues (does not break playing 
        DRM content, this 
	metadata is stored elsewhere I do not recall, but also links device to Apple ID DSID)

	defaults delete ~/Library/Preferences/com.apple.iTunes.plist StoreUserInfo
	defaults delete ~/Library/Preferences/com.apple.iTunes.plist WirelessBuddyID

~/Library/Containers/com.apple.appstore/Data/Library/Preferences/com.apple.commerce.knownclients.plist

	Check this directory and clear relevant metadata

~/Library/Preferences/com.apple.commerce.plist

	CLEAR STORE METADATA CONTAINED IN HERE

QuickTime Player X keeps a permanent log of ALL media played in its container preference file

Note that ~/Library/Preferences/com.apple.QuickTimePlayerX.plist does not contain sensitive metadata usually, but check anyway.

Apple sneakily writes metadata to container preference file instead...

~/Library/Containers/com.apple.QuickTimePlayerX/Data/Library/Preferences/com.apple.QuickTimePlayerX.plist MGRecentURLPropertyLists

	conains a vast amount of info...

	check the entire file, in case i missed something...

RECOMMEND CHMOD 400 AND CHFLAGS UCHG ON ~/Library/Containers/com.apple.QuickTimePlayerX/Data/Library/Preferences/com.apple.QuickTimePlayerX.plist

	QUICKTIME FUNCTIONS PERFECTLY WITH THIS SETUP

**Comment by drduh** [comment]
This is a really excellent list. I'll definitely write this into its own section of the guide, I think. Thanks!

**Comment by TraderStf** [comment]
@iosecure nice work! Thanks to all big guys (and girls ;-)

FYI... quickly, I have to smash few phishing spammers. 

[fsmonitor](http://fsmonitor.com) monitors all changes in the file system

HandsOff! app can also help to track third-parties apps which are a bit too invasive...

I'm testing the beta of F-Secure XFENCE (former ?) can help too, but don't waste your time, few bugs but missing 'access' to positive-rules...

For the rookies, take a look to 
CastleGuard2
BlockBlock
Find Any File
Process Monitor
SpotFiles
Suspicious Package
https://www.rbcafe.fr/software/tracking/ yes in rb :-p
http://www.tyrhex.com

**Comment by aes512** [comment]
@iosecure - You have a typo: `chflag -R uchg /.DocumentRevisions-V100` should be `chflags -R uchg /.DocumentRevisions-V100` (missing the "s" in chflags).
