### ISSUE TITLE
Siri Privacy

### ISSUE THREAD

**Issue by pgeorgan** [drduh/macOS-Security-and-Privacy-Guide#258]
Consider updating to reflect Siri Suggestions having it's own placeholder in System Pref. 

![siri](https://user-images.githubusercontent.com/10644662/32278486-4411e79c-beec-11e7-916f-0f0b115df362.png)

**Comment by drduh** [comment]
I'm not seeing that menu. Is this on High Sierra? Does one need to be signed into or have Siri enabled to see it?

**Comment by netflash** [comment]
Here's from Sierra 
<img width="612" alt="screenshot 2017-12-22 11 18 18" src="https://user-images.githubusercontent.com/2478391/34310015-e3f07338-e709-11e7-9584-3a53efd1c7d1.png">

**Comment by netflash** [comment]
And from High Sierra
<img width="633" alt="screenshot 2017-12-22 11 19 17" src="https://user-images.githubusercontent.com/2478391/34310056-21dd7524-e70a-11e7-8e84-6aaaf7028453.png">

**Comment by pgeorgan** [comment]
I was simply pointing out it would be helpful to mention to readers that "Siri Suggestions & Privacy" is another place to check for privacy settings... It was not clear to me from your musings.
