### ISSUE TITLE
python could not install any script 

### ISSUE THREAD

**Issue by BlackTighr** [drduh/macOS-Security-and-Privacy-Guide#261]
I installed `python` from `brew`

    brew install python

then installed pip

    sudo easy_install pip

in Terminal 

    $ which easy_install
    /usr/bin/easy_install

    $ which python
    /usr/bin/python

But then when I want to install any Python script I get this:

    Searching for pexpect
    Best match: pexpect 4.2.1
    Adding pexpect 4.2.1 to easy-install.pth file
    
    Using /Library/Python/2.7/site-packages
    Processing dependencies for pexpect
    Finished processing dependencies for pexpect
    Searching for pycrypto
    Best match: pycrypto 2.6.1
    pycrypto 2.6.1 is already the active version in easy-install.pth
    
    Using /Library/Python/2.7/site-packages
    Processing dependencies for pycrypto
    Finished processing dependencies for pycrypto
    Searching for pyopenssl
    Best match: pyOpenSSL 0.13.1
    pyOpenSSL 0.13.1 is already the active version in easy-install.pth
    
    Using /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
    Processing dependencies for pyopenssl
    Finished processing dependencies for pyopenssl
    Searching for pefile
    Best match: pefile 2017.9.3
    pefile 2017.9.3 is already the active version in easy-install.pth
    
    Using /Library/Python/2.7/site-packages
    Processing dependencies for pefile
    Finished processing dependencies for pefile

Here's an image of the problem:

[![][1]][1]

  [1]: https://i.stack.imgur.com/r1jSX.png

**Comment by rawtaz** [comment]
How is this related to the macOS security guide? Seems like you asked this in the wrong forum. You could have a go on Freenode, in the channel #python.

That said, I'm not sure what you mean is the actual problem anyway. There's no error output in what you've shown.

**Comment by aes512** [comment]
I'm guessing he's trying to install the Social Engineering Toolkit on macOS :s

**Comment by drduh** [comment]
Have you tried turning it off and back on again?

**Comment by BlackTighr** [comment]
Yes i wanna install Social Engineering Toolkit on macOSX
