### ISSUE TITLE
Secure Virtual Memory and hibernatemode

### ISSUE THREAD

**Issue by kristovatlas** [drduh/macOS-Security-and-Privacy-Guide#262]
A GitHub user brought up the following concern for my MacOS security tool:

> Setting the hibernation mode to 25 would cause the system to write the RAM content to the > /var/vm/sleepimage - but this file is not encrypted?
> 
> Newer Macbooks introduced the Secure Virtual Memory.
> 
> Reconsider to set the hibernation mode?

https://github.com/kristovatlas/osx-config-check/issues/189

Anyone have insight into this?

**Comment by drduh** [comment]
I don't see this as an issue with FDE enabled. Please reopen if I missed something.
