### ISSUE TITLE
Root account with blank password enabled by default from High Sierra onwards

### ISSUE THREAD

**Issue by hairychris** [drduh/macOS-Security-and-Privacy-Guide#263]
~~Two potential solutions:~~

~~1. Instruct user to disable root account~~
~~2. Instruct user to password protect root account.~~

**2017-12-01: These instructions are out of date now Apple have released a security update.**

After reviewing [Apple's official instructions](https://support.apple.com/en-us/HT204012) (see below) the only solution is to set a secure password for the root account. To be 100% clear just disabling the root account will NOT fix this bug.

Do NOT disable the root account after setting a password as this will recreate the account with a blank password, Apple really shit the bed on this one.

It also states on the page:

> It's safer to use the sudo command in Terminal instead of enabling the root user.

We don't ever need to use the root account directly so we can set a randomised password:

`cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 60; echo | xargs -I rootpw sudo dscl . -passwd /Users/root rootpw`

Happy to writeup and put in a pull request once we decide on the correct course of action.

It would appear that Apple are going to fix this themselves but we might need some additional steps (e.g. once fixed disable root account on High Sierra)

**Comment by AnachronicNomad** [comment]
I was able to reproduce this bug a few times, the fix that ended up working was to first enable the root account with a strong password, then disable it again. You can enable the root user using ```dsenable```, then disabling with ```dsenable -d```. 

I remember reading (but I can't find the source of that information now) that macOS 10.12+ ships with the root user disabled or removed as default; but the bug in System Preferences revolves around how it will trigger the recreation of a new root user with an empty password. So it seems to make sense that the fix would involve first enabling the root user and changing its password, then disabling it once its already active.

**Comment by ansell** [comment]
Apple's official steps (including both proposed solutions) are at:

https://support.apple.com/en-us/HT204012

**Comment by hairychris** [comment]
Apple released this statement:

“We are working on a software update to address this issue. In the meantime, setting a root password prevents unauthorized access to your Mac. To enable the Root User and set a password, please follow the instructions here. If a Root User is already enabled, to ensure a blank password is not set, please follow the instructions from the ‘Change the root password’ section.”

So you are correct in saying solution 1 alone is not actually a solution at all, a combination of both solutions is required, I'll update the original issue.

**Comment by TraderStf** [comment]
https://9to5mac.com/2017/11/28/how-to-set-root-password/
here they use to quickly change the pw
/System/Library/CoreServices/Applications/Directory Utility.app

**Comment by ansell** [comment]
There are some worrying comments floating around about a root account (with no password) possibly being automatically created in some situations if the disable method is used, so enabling and setting a secure password seems safest for now.

Also, I haven't been able to replicate any of the issues on Sierra, and I haven't noticed commentators so far saying they could replicate on Sierra either.

**Comment by TraderStf** [comment]
@hairychris on 9to5 (see above) I think that's what they do, use sudo at the end.

**Comment by TraderStf** [comment]
Forget my (deleted) comments.

**Comment by drduh** [comment]
As pointed out in #251, I have not yet upgraded to High Sierra and do not recommend others do, either. In fact, a part of me doubts I will use macOS for any serious work in the future in light of this bug; I've already ceased using Apple products for certain security- and privacy-sensitive works in light of recent, puzzling and downright disturbing incidents.

As no amount of hardening one may do could prevent a security vulnerability this stupid and negligent, I regret to say it may be entirely likely this guide will need a new owner if it is to be kept up to date with future macOS releases. As a privacy-minded user, I believe I can and should act in accordance with my values, even if this means no longer using macOS, unfortunately.

**Comment by dnwe** [comment]
@drduh are you starting to use hardened debian or some bsd for those may we ask?

**Comment by rawtaz** [comment]
@drduh FWIW you are not alone. My current Mac is the last one I will own. Unfortunately I bought it while I was still heavily invested in the Mac ecosystem, but I'm slowly working towards replacing it with a Linux or BSD desktop in instead. Unfortunately doing so has proven to be really hard, even with the nicest of Linux distros. But I'm not giving up :)

**Comment by TraderStf** [comment]
iPhone, iPad first...

**Comment by drduh** [comment]
@dnwe I am currently using hardened Debian on an older x200 I found locally and freed from Intel ME, for what it's worth; though eventually I'd like to get OpenBSD fully working on it.

**Comment by nadavP3** [comment]
@drduh
Any thoughts about AMD’s mobile Ryzen based laptops? (No vPro or Intel ME there, plus much newer hardware {m.2 PCIe NVMe SSD, DDR4, better screens.. more performance .. etc})

**Comment by drduh** [comment]
My understanding is, the situation with AMD is not much better - https://libreboot.org/amd-libre.html

**Comment by davidpelayo** [comment]
A security update from Apple was just released https://support.apple.com/en-us/HT201222.

**Comment by nadavP3** [comment]
@drduh I would love to read your take on System76's yesterday's announcement regarding their efforts in disabling Intel ME on their systems (Intel gen 6/7/8 based)

http://blog.system76.com/post/168050597573/system76-me-firmware-updates-plan

**Comment by ansell** [comment]
This is a report that the bug may not have been integrated properly and came back for some users depending on the sequence of updates and whether they restart manually after if they used one sequence. Very worrying...

https://www.buzzfeed.com/nicolenguyen/the-root-login-bug-is-back-in-the-latest-macos-update

**Comment by TraderStf** [comment]
> If you recently updated from macOS High Sierra 10.13 to 10.13.1, reboot your Mac to make sure the Security Update is applied properly

https://www.wired.com/story/macos-update-undoes-apple-root-bug-patch/

**Comment by nadavP3** [comment]
A little OT (sorry!)
But, besides System76, if I am reading this correctly, Dell is now also featuring laptops with Intel ME disabled:

Its given on some models as a selection of 1/3 of the following:
> No Out-of-Band Systems Management $0

> Intel vPro™ Technology’s Advanced Management Features +$20.92

> Intel vPro™ - ME Inoperable, Custom Order +$20.92

check it out here:
[Latitude 14 5414 laptop](http://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/new-latitude-14-rugged/spd/latitude-14-5414-laptop/xctol541414us)

[Latitude 13 7380 laptop](http://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/new-latitude-7380/spd/latitude-13-7380-laptop/cto04l738013us?selectionState=eyJGUHJpY2UiOjE3NTguMCwiT0MiOiJjdG8wNGw3MzgwMTN1cyIsIlF0eSI6MSwiTW9kcyI6W3siSWQiOjQ5LCJPcHRzIjpbeyJJZCI6Ik5PVlBSTyJ9XX0seyJJZCI6NzQ5LCJPcHRzIjpbeyJJZCI6IkNJN1NNTCJ9XX1dfQ%253D%253D)

[Latitude 7202 tablet](http://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/latitude-12-rugged-tablet/spd/latitude-7202-tablet/cal12rw8pc)

[latitude 14 7414 laptop](http://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/new-latitude-14-rugged-extreme/spd/latitude-14-7414-laptop/xctol741414us)

[latitude 12 7214 2-in-1 laptop](http://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/new-latitude-12-rugged-extreme/spd/latitude-12-7214-2-in-1-laptop/xctol721412us)

**Comment by nadavP3** [comment]
Another alternative:
ARM based laptops?
https://www.anandtech.com/show/12119/microsoft-launches-windows-10-on-arm-always-connected-pcs
Just format and install some other OS

:x

**Comment by lebensterben** [comment]
@nadavP3 it's not wise to recommend windows os even in this situation. For privacy and security purpose, one should always stay away from windows.

**Comment by nadavP3** [comment]
@lebensterben 
I am not recommending Windows or any other OS at this point.

The reason that I listed the above system is to show that perhaps there are new/up to date systems out there that come with the claims of having this particular vulnerability-as-a-feature disabled.

Which maybe some of the readers/contributors of this thread/issue aren't aware of (As otherwise the impression that I was getting here was that you have to revert to much older hardware which might not be compatible with some user's requirements).

Naturally there are is still a long way to go before any system could be both as secure as, and as useable as Apple's offering.

To be perfectly clear, I would love nothing more than to have Apple jump in on this and announce that all future systems will come without this vulnerability (fleet management can be achieved via other means [such as costume image deployment] without sacrificing security after all)
If that was not to happen, and if this "feature" proves to be as big of a deal as we suspect it to be, if the info-sec security was to come together and .. pick an OS (Debian/OpenBSD or even ubuntu) and create (at the very least) a guide that would allow it to otherwise match the security level that is possible on MacOS, I'd be happy* to jump ships (*happy is not an accurate statement since the hassle that OS swap for daily/main machine entails a heck of a time sink but ... willing/able and motivated to do so)
I suppose at the end of the day its all about tradeoffs
