### ISSUE TITLE
app store是需要AppleID的

### ISSUE THREAD

**Issue by r0ysue** [drduh/macOS-Security-and-Privacy-Guide#265]
App Store requires a Apple ID and password signed in

**Comment by drduh** [comment]
It is not necessary to use the App Store for any part of this guide.

**Comment by r0ysue** [comment]
you can search in the README.md:76 ,which says "macOS system updates can be completed using the App Store application, or the `softwareupdate` command-line utility - neither requires registering an Apple account."

but it turns out you have to signed in with an Apple ID .

**Comment by drduh** [comment]
That's not accurate; you do not need an Apple ID to use the `softwareupdate` command, unless something has changed. Can you share an error or message you get when attempting the updates?
