### ISSUE TITLE
Someone to maintain osx-config-check?

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#267]
https://github.com/kristovatlas/osx-config-check

For non-techies, it's difficult to know if macOS is (and router, network, vpn... are) correctly set.
OSX-CC is no more updated since 2 years.

Thanks

**Comment by lebensterben** [comment]
I'm using lynis to verify my system configurations. It's a commercial software but free for non-commercial use. It's frequently maintained and updated, and is available to various operation systems. The only downside is some of it's recommendation are more suitable for linux distributions. Maybe someone could adopt this project but borrow some ideas from lynis?

**Comment by TraderStf** [comment]
@lebensterben Thanks. I have use it and mention it several months/years ago.
Had to change a small explanations to install it on mac, they update it after I had contact them.
Was ok on mac, good recommendations.
Their new plugins seems interesting, firewall, rules, tables... will take a look.

**Comment by drduh** [comment]
Please file this issue against that repository.
