### ISSUE TITLE
Note on homebrew installation guide for High Sierra

### ISSUE THREAD

**Issue by crichez** [drduh/macOS-Security-and-Privacy-Guide#270]
While following your instructions on installing homebrew on High Sierra, `brew update` returns `Error: Git must be installed and in your PATH!`
Installing command line developer tools restores Git to working order: `xcode-select --install`

MacOS High Sierra 10.13.2
2017 15" MacBook Pro

Thanks for a really thorough guide!

**Comment by drduh** [comment]
Did you see the note about the same in the Homebrew section? ("If you have not already installed Xcode or Command Line Tools, use `xcode-select --install` to download and install them from Apple.")

Or do you mean you had to run the xcode-select command again after homebrew was installed?

**Comment by crichez** [comment]
Nope, that's 100% my bad 🙃

Closed!
