### ISSUE TITLE
*OS Internals, Vol I, User Space, by Jonathan Levin

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#272]
While looking for info about EthCheck, found this:

*OS Internals, Vol I, User Space, by Jonathan Levin
https://eclecticlight.co/2017/12/30/essential-reading-os-internals-vol-i-user-space-by-jonathan-levin/

https://twitter.com/hashtag/MOXiI

http://newosxbook.com/2ndUpdate.html

**Comment by TraderStf** [comment]
https://eclecticlight.co/ is full of rare info. Several tools also, e.g.:

https://eclecticlight.co/2017/12/21/lockrattler-4-1-for-el-capitan-sierra-and-high-sierra-is-now-finally-released/

**Comment by drduh** [comment]
I ordered both of Jonathan's books and will probably make a lot of changes once I digest them. Thanks.
