### ISSUE TITLE
DNSCrypt is now unmaintained

### ISSUE THREAD

**Issue by savyajha** [drduh/macOS-Security-and-Privacy-Guide#273]
As per [this](https://twitter.com/jedisct1/status/928942292202860544) tweet, seems like DNSCrypt is now unmaintained. [Here](https://www.reddit.com/r/linux/comments/7owb1s/psa_dnscrypt_is_now_abandoned/) is a reddit discussion on the same. Might be a good idea to discuss alternatives?

**Comment by drduh** [comment]
There's now [DNSCrypt-Proxy 2](https://github.com/jedisct1/dnscrypt-proxy).

**Comment by savyajha** [comment]
Huh. Interesting. It's been re-written from scratch. Might be worth checking if it's worth replacing dnsmasq with as well, seeing it seems to have better support for caching ([according to the author](https://github.com/jedisct1/dnscrypt-proxy/wiki/differences-with-v1)).

**Comment by drduh** [comment]
I've been using the new version in conjunction with Dnsmasq and it's been working well. I'll go ahead and recommend it in the guide.

**Comment by savyajha** [comment]
Just to ask, why in conjunction with dnsmasq? dnscrypt also implements a cache.

**Comment by drduh** [comment]
Just more familiar with dnsmasq syntax and options, but I'll look closer at what Dnscrypt v2 offers for the same.

**Comment by strogonoff** [comment]
FWIW I believe DNSCrypt-Proxy 2 is what you get if you `brew install dnscrypt-proxy` per instructions in the state they already were a couple months ago.

```console
tonys:~$ brew info dnscrypt-proxy
dnscrypt-proxy: stable 2.0.15 (bottled), HEAD
Secure communications between a client and a DNS resolver
https://github.com/jedisct1/dnscrypt-proxy
/usr/local/Cellar/dnscrypt-proxy/2.0.11 (12 files, 11.6MB) *
  Poured from bottle on 2018-05-11 at 01:25:13
```
