### ISSUE TITLE
macOS High Sierra App Store Preferences Can Be Unlocked Without a Password

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#275]
FYI, just in case you miss it... 😜
Do you think apple is using M$ tools to debug 🔮

https://thehackernews.com/2018/01/macOS-high-sierra-password.html

**Comment by drduh** [comment]
High Sierra is full of bugs, errors and oddities. This is why I have not yet updated the guide to macOS 10.13; I am waiting for incremental releases to iron out the kinks and get its shit together. I advise other macOS users to do the same, also sharing your feedback with Apple.

**Comment by nadavP3** [comment]
Regarding the wait for High Sierra:
https://forums.macrumors.com/threads/my-experience-trying-to-install-high-sierra-on-mac-pro-with-hardware-raid.2072799/

I highly recommend reading "jer2eydevil88" experience with High Sierra on classic mid-2010 Mac Pro that is on Enterprise Support, he had a back and forth with Apple's Enterprise Support team. (you can skip the first few posts on that thread)

Non traditional storage setups*, as in, setups that haven't shipped with a Mac, don't really work (either os is broken and cannot be booted, os installer fails to start, or systems becomes incompatible with future software upgrade process (so no 10.13.2))

* using RAID 0 or 1 on a MBP/iMac (where the user removed the DVD and original HDD and installed two SSDs)
* using (on classic mac pro) raid controller and a few drives.

example:
0. MBP /w RAID 0 (2 drives), formatted as HFS+ running Sierra 10.12.6 without issues
1. High Sierra (10.13) wouldn't install as "raid drives aren't supported"
2. This error can be bypassed by cloning the raid into single disk (even external), booting from the single disk, then upgrading to High Sierra, then cloning from the single disk, back to the raid
it would boot and work mostly okay.
3. but 10.13.2 update is incompatible with this setup, so updating results in "some updates could not be installed" message after user logs back in (no matter what action you take, safe boot, new admin user, using external disk, using terminal, the store, the actual files from apple's website, the combo/regular/supplemental), system stays on 10.13.1 (future attempts (so #2 and above) to update to 10.13.2 would display in the app store as "update 10.13.2 to 10.13.2")

While High Sierra experience with different RAID setup feels like a pc Hackintosh, on the same exact setup, Sierra 10.12.6 works flawlessly

**Comment by nadavP3** [comment]
@drduh 
https://twitter.com/objective_see/status/953431798100393985

“
Apple's AMDRadeonX4150 kernel extension appears to suffer from an out-of-bounds read. Which (amongst other things) can cause a kernel panic even on latest version of macOS (10.13.2) 🤐 “
