### ISSUE TITLE
macos malware - OSX/MaMi - dns hijacker

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#276]
Spread macos malware - OSX/MaMi

See https://objective-see.com/blog/blog_0x26.html

AVG detects it and puts it in quarantine, virustotal still reports 4/5 domains as ok...

Reverse Whois 'consible@mail.ru'

Domain Name	Creation Date	Registrar
angeing.info	2017-05-30	DANESCO TRADING LTD.
definitial.info	2017-05-30	DANESCO TRADING LTD.
humption.info	2017-05-30	DANESCO TRADING LTD.
lilovakia.info	2017-05-30	DANESCO TRADING LTD.
regardens.info	2017-05-30	DANESCO TRADING LTD.

**Comment by TraderStf** [comment]
Domains registred by 'prolone2@yahoo.com'
Domain Name	Create Date	Registrar
accessful.info	2017-05-30	evonames.com
gorensin.info	2017-05-30	evonames.com
honouncil.info	2017-05-30	evonames.com
sincentre.info	2017-05-30	evonames.com
squartera.info	2017-05-30	evonames.com

**Comment by drduh** [comment]
I'll make mention of it when working on the Virus and Malware section (see #239).

**Comment by TraderStf** [comment]
just checking and found this new crap, but all seem off.

https://viewdns.info/reversewhois/?q=consible%40mail.ru

Domain Name | Creation Date | Registrar

angeing.info | 2017-05-30 | DANESCO TRADING LTD.
definitial.info | 2017-05-30 | DANESCO TRADING LTD.
humption.info | 2017-05-30 | DANESCO TRADING LTD.
lilovakia.info | 2017-05-30 | DANESCO TRADING LTD.
regardens.info | 2017-05-30 | DANESCO TRADING LTD.

A bit different
https://www.domainiq.com/email?consible@mail.ru#domains
https://domainbigdata.com/mail.ru/mj/Ofl7BEQ1_KQu0-9f1whQNQ

Vladislav Kakoshin | is associated with 5 domains (SAME 5)
