### ISSUE TITLE
Survive to update 10.3.3 crash - updated feb 20 ”Indian” update

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#277]
This might perhaps help some of you.
When updating from 10.3.1 to 2, I got a huge mess, crash, finally had to resintall using MacRecovery.
Waste too much time to figure out why...

Today, updating from 10.3.2 to 3, again, imac stucks during the installation ~"blabla calculating time"
wait 15 min, nothing.
Force Reboot several time, same.
Shift-reboot, can enter in 10.3.2, was supposing some 'booting' items, like anti-virus... were the cause.
I manually delete all folders, launch daemons, agents... of
google santa, old-beta of xfence, avg and malwarebyte am.

Reboot, same 'calculating'
cmd-v reboot, see the command lines but suddenly jumps to 
the usual install dialog, once again 'calculating'

Disconnect all 3 external HD.
Reset PRAM at reboot by holding cmd-opt-p-r
The 'full install' appears (don't know the name, just as if you install a brand new mac)

43 minutes remaining, it took at least 4 minutes to pass to each next minute on screen, 42, 41...37
suddenly time remaining was 18. cool time travel 👎 

Then the dialog 'installing on HD' and the usa-flag appear on top right, wifi not connected (I have no ethernet cable, only wifi; The HD is a fusion drive).

Extremely slow, seems nothing happens, no noise of course, took at least 20 min.
Then the login screen appears, it's 10.3.3

😜🤪

Seems reseting the PRAM solves this mess.

Perhaps the problem was due to the fact that few OS before (10.1 ?) I set the system on a very fast external drive, then bought an imac 5K (fusion drive) and something get confused...
Though if I remember well, I had major upgrades on the imac...

Hope this help.

**Comment by nadavP3** [comment]
What year is your iMac?

I have seen some issues with 10.13.2 on MBP mid-2010 and on classic MacPro, not with High Sierra (10.13.0), not with 10.13.1 ... but spesificly with the installation of 10.13.2 (fails after 2min, reboots, system stays in 10.13.1, app store starts reporting the update as "10.13.2 to 10.13.2", all typical common work around fails (installation source[app store, terminal, pkg, combo, supplemental, plain], from internal disk, from external disk, on raid, on single drive, on APFS on HFS+,  after clean install, single user mode, PRAM reset, new user)
What I saw that worked was booting from 10.13.2 that was installed by another (and newer) Mac (as early as 2011 MBP for the mid-2010 MBP), but system became unusable when this is done (takes 45-1hr to boot up, opening anything takes a few attempts[safari/about this mac, would "bounce" a few times and vanish .. after few attempts it would open but take 5-15min to do so, even on internal SSD, RAM usage also goes up with system idle at 7gb ram used for no clear reason)
All of this while
10.12.6 + 2018 security update works flawlessly on both MBP mid-2010 and classic MacPro
booting into 10.12.6 that was installed on another Mac also works fine without any noticeable issues
booting into 10.13.0 or .1 that was installed by another Mac also works fine without issues.

Almost as if they broke support for this two older systems with the .2 update 
![image](https://user-images.githubusercontent.com/17965345/35346695-bee4d99c-00e7-11e8-9536-d911b734e769.png)

**Comment by TraderStf** [comment]
iMac (Retina 5K, 27-inch, Late 2014)

The only recommendation I can made is to wait several minutes at each steps, my internet is fast 120 Mbps.
e.g. after a reboot, the app store - update panel took at least 2 minutes to show again that I have to update to 10.3.3, normally it's 10 seconds

I am wondering if the '43 min' episode was the same but during the normal/first/rebooted update, that is black screen with progress bar.
Perhaps had to wait that long... go figure 🤯

I think my imac is faster than before.
A keyboard bug has been solved, briefly:
mac bought in France, old-cable-ext-keyboard in Belgium, can never set the prefs correctly, was always 'French', not French Extended or whatever, though working perfectly. Now it was set to French, but was not working ! no keys, must change it to Fr-Ext and everything is fine.
Normally you must have Fr-Fr Fr-?Be? Fr-Ch Fr-Ca... few keys are different. They probably group few FR-*

Since 1983 I never so many troubles with mac

**Comment by TraderStf** [comment]
I finally figured out why latest Apple updates can't be installed.
Hard Disk is locked!

Seems lot of users have this problem which is linked to the Fusion Drive, saw messages from 2014.

Using CMD-OPT-R (=from interner), not just cmd-r = same as root disk, to make a full new installation is useless
it takes 90+ minutes but at the end, the 10.13.3 'Indian character' update still has to be done...

USELESS: 
Booting from another HD/whatever and
- using diskutil (sorry diskuseless) or TechTool Pro is useless.
- sudo chflags 0 /Volumes/*  then  chmod a+rx /Volumes/*
- Paragon HD manager neither

Google it, seems the only solution is to erase and reformat!
Seems nothing detects the boot volume is locked.

But I'm wondering why during my previous Apple update, finally a cmd-R (not opt-r) was ok, all updates were installed, perhaps today it was too soon, Apple did not yet 'include' it in the from-web-update...

Could it be SIP which blocks?

FYI, if you are a poor non-us ascii user, in 'boot-situations' you have to type as if you were using an US keyboard.
Use the ~boot from internet, in the network (not password) field, you can type and see all the characters/keys you need until you find those used in your password...🤩

**Comment by TraderStf** [comment]
I reopen because **RepairHomePermissions** has solve the problem.
All other things I have tried, including terminal... did not.
Updates are now applied without problem.

https://eclecticlight.co/downloads/

> RepairHomePermissions
>repairs the permissions in your Home folder (macOS Sierra)
>The only app which will help you repair the permissions in your Home folder, which can fix a variety of different problems, according to Apple.

**Comment by TraderStf** [comment]
I reopen it as saw several poor users who are still affected by this 🐞
