### ISSUE TITLE
Question: MacOS Internet Recovery and Security

### ISSUE THREAD

**Issue by whitemolecule** [drduh/macOS-Security-and-Privacy-Guide#278]
Hello,
I am currently living at a university where network is monitored (and possibly altered) by the network administrators.
My question is, does apple verifies integrity of  (or download securely) downloaded recovery image via MacOS internet recovery  and MacOS full install image downloaded via that internet recovery?
As far as I know, full install image is downloaded over unencrypted HTTP connection but I don’t know if there is a some kind of verification step.
Also I don’t know if Apple somehow verifies recovery image downloaded with cmd+option+R 
I can download recovery image over LTE using my phone’s personal hotspot but full install image is too large to download over mobile connection.
So, is it safe to use internet recovery on a network that I can’t trust 100% ?

EDIT: I am on latest MacOS High Sierra and MBP 2016 without touchbar and touchid.

Thank you for answers (and the guide)

**Comment by rawtaz** [comment]
If you are concerned about the integrity/security of your Internet connection, instead of relying on image verification of your download as possibly done by Apple, you can simply use a VPN or Tor to download the data. That's a better protection against your network admins :-)

Nothing is ever failsafe though so make sure you verify the image yourself regardless.

**Comment by whitemolecule** [comment]
Thanks for the answer, I always use a VPN after installation of MacOS, but it is hard to use one while doing internet recovery. I am probably over cautious but I wonder if Apple implemented a security mechanism or left us unprotected while using internet recovery.

**Comment by rawtaz** [comment]
I see. Well, you can always simply use a little Raspberry Pi or other small device that you make your Mac go through when not being able to use a VPN itself. And on that Rpi or similar have a VPN of course.

Personally I never use Internet recovery when reinstalling my Macs, I always use an image I burnt to a USB drive. That way I can always have the version I want to install, usually the latest of course.

**Comment by drduh** [comment]
Hi @whitemolecule 

You are asking a very good question. I can't assert that the right verification steps happen during Internet Recovery installation, but I would be surprised if at least some checks didn't exist. Still, it would take a pretty sophisticated attacker to orchestrate the man in the middle attack you are thinking of. As such, I probably wouldn't worry too much about that. Here are some ideas to put your mind at ease:

* Set up a device to act as a router and either VPN to a trusted network or dump packets to see a MITM. Check my PCEngines guide for suggestions.
* You can download the InstallESD.dmg file from somewhere else and build the image yourself, then restore it over USB or the local network from Recovery Mode.
* You can power off your Mac after it's done downloading the image, then extract the InstallESD.dmg file from the staging disk to another computer, verify its integrity or use it to build an image also.

Hope this helps you!
