### ISSUE TITLE
Activating FV2 - Why not DEK method?

### ISSUE THREAD

**Issue by metagoose** [drduh/macOS-Security-and-Privacy-Guide#285]
Excellent guide and I appreciate the work and effort Dr.Duh has sacrificed in order to maintain this. 

Anyone know why the guide does not recommend the DEK approach to FV2 encryption? The only reason I can think of is that maybe it does not allow you the option to generate extra entropy? 

> Consider the use of a disk password a special use case where a single passphrase is used to generate a single DEK to wrap and unlock the corresponding KEK or volume. A volume protected in this manner could be thought of as a FileVault-enabled volume with a single, non-OS authenticated user. A disk password prohibits separate users from unlocking the volume with their own password and prevents the use of an IRK for access to that volume.

**Comment by drduh** [comment]
I don't know much about this method. Please send a PR with more information if you think this will be useful to have in the guide.

**Comment by HazCod** [comment]
From Wikipedia, the DEK method in FV2:

```
If a volume to be used for startup is erased and encrypted before clean installation of OS X 10.7.4 or 10.8:

there is a password for the volume
the clean system will immediately behave as if FileVault was enabled after installation
there is no recovery key, no option to store the key with Apple (but the system will behave as if a key was created)
when the computer is started, Disk Password will appear at the EfiLoginUI – this may be used to unlock the volume and start the system
the running system will present the traditional login window.
```
