### ISSUE TITLE
Doubling FV Encryption

### ISSUE THREAD

**Issue by metagoose** [drduh/macOS-Security-and-Privacy-Guide#286]
I am a huge believer in multiple layers of encryption. I use always full disk encryption. This setup has literally saved my life. For me personally, I always make the assumption that a determined and motivated adversary will be able to create a situation in which they could target my computer for physical acquisition in a powered on authenticated state.  I use multiple layers of encryption to mitigate the chance of a full compromise for this specific scenario (targeted PC for physical acquisition). 

One of the technical white papers from apple on Filevault does recommend in some scenario's (DEK approach, multi-user PC) you consider using both Filevault 2 encryption and Fivevault 1 simultaneously. The first provides a full disk encryption and the second provides additional layer of encryption over the user folder. I can't find any information documenting this process. I think it would be of great value to the privacy guide if it could be figured out. Put as many eggs in as many baskets as possible! If your threat model requires it. Anyone have any ideas how to get this working?

**Comment by rawtaz** [comment]
Set up FileVault for your FDE, and then create encrypted images that you use to store documents in?

**Comment by victorberland** [comment]
I usually have various VeraCrypt containers for important documents that need two layers of encryption. It's probably overkill for me, but it's nice to know when travelling. I don't quite see how one would be able to use both FV1 and FV2 at the same time. The settings panel only allows you to enable or disable FV2.

**Comment by drduh** [comment]
Feel free to send PRs with recommendations for additional encrypted containers/layers. I think FDE covers most users' needs, however.
