### ISSUE TITLE
Screensaver instructions do not work on High Sierra

### ISSUE THREAD

**Issue by mtibben** [drduh/macOS-Security-and-Privacy-Guide#290]
```
$ defaults write com.apple.screensaver askForPassword -int 1

$ defaults write com.apple.screensaver askForPasswordDelay -int 0
```

These instructions for setting the screensaver settings do not work on High Sierra

There does not appear to be any simple way to set these settings via CLI

See:
- https://stackoverflow.com/questions/45867402/macos-10-13-high-sierra-no-longer-stores-screensaver-settings-in-com-apple-scr 
- https://blog.kolide.com/screensaver-security-on-macos-10-13-is-broken-a385726e2ae2

**Comment by HazCod** [comment]
Doesn't `defaults write com.apple.screensaver askForPassword -bool TRUE` work?

**Comment by alichtman** [comment]
I ran into this issue while I was developing [stronghold](https://www.github.com/alichtman/stronghold) and found that a restart is necessary for changes to be applied. But it only works sometimes? I'm still puzzled by how this works. @mtibben

**Comment by drduh** [comment]
Please reopen or send a PR if it's an issue on the latest release.
