### ISSUE TITLE
Question: A binary with broken signature in the HS Installation app

### ISSUE THREAD

**Issue by whitemolecule** [drduh/macOS-Security-and-Privacy-Guide#296]
Hi there,
After verifying MacOS Installer to install MacOS High Sierra (v 10.13.4) I realized one binary's digital signature in the installer marked as invalid by VirusTotal.
Install macOS High Sierra.app/Contents/MacOS/InstallAssistant_springboard
SHA1SUM: d4e2a6f8110fa3ab6b8a684df3b83f70bfaab2b1 
SHA256SUM: 24d8699e6500ea8e0814bd4a9b56ecfa88f607a9e2c95b561c0d76e03085a721

https://www.virustotal.com/#/file/24d8699e6500ea8e0814bd4a9b56ecfa88f607a9e2c95b561c0d76e03085a721/details

Though, it looks like it's certificate chain verifies back to Apple Root Certificate, I wanted to ask if there is a problem with VirusTotal or Apple's signing procedure.

Other binaries in the same folder are marked as signed correctly such as Install macOS High Sierra.app/Contents/MacOS/InstallAssistant
https://www.virustotal.com/#/file/01c44989ed32131b5af298aa5db355886c138ef89bd4ef7b19cb4a49f8e67c5f/details

It might be dump question but, could you please verify checksums of the same file if you have installation app nearby?

Thanks.

**Comment by drduh** [comment]
I believe the issue has come up before with this exact file and it was nothing to worry about. You could always try downloading a more recent version of macOS now.
