### ISSUE TITLE
FYI Cheap U2F key - GitHub logging attempts - Leaking VPN? - Behavioral ads

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#297]
**Cheap certified U2F key**
https://hypersecu.com
Bought the K8-mini (8€ amazon.fr)
(the green light is always on, quite strong 😎 blinks when accessed, fits perfectly under imac keyboard)
Must use terminal to install it to use it for macos login.
Safari does not support U2F, Chrome and FF ok.
Located in 5👁 CA&US 📡

_Sites/apps and U2F_
https://fidoalliance.org/certification/fido-certified-products/
https://www.yubico.com/solutions/#

**GitHub logging logs**
Can see logging attempts, click for details, time... in 'Settings - Security - History'.
I suggest to report the 'bad' IPs to https://www.abuseipdb.com

**Leaking VPN?**
https://vpntesting.info

**Behavioral  Ads**
If you trust them...
http://www.youronlinechoices.com
Choose your language, third menu to configure.

**Comment by drduh** [comment]
Please send a PR if you see a good place to add this to the guide.
