### ISSUE TITLE
XMPP, OTR, and Adium is out of date

### ISSUE THREAD

**Issue by nsuchy** [drduh/macOS-Security-and-Privacy-Guide#299]
The XMPP Client Adium (only XMPP Client I've found for macOS that supports OTR) has not been updated since July 2017, the project seems abandoned and the trac server to download source code is offline. What can/should be done about this issue?

**Comment by kxpvcr** [comment]
[This list of alternatives](https://alternativeto.net/software/adium/?platform=mac) isn't very promising. Maybe Pidgin?

**Comment by nsuchy** [comment]
@kxpvcr Only works if you launch by command line and on macOS looks ugly in comparison. Right now I just use ChatSecure on my phone - wish there was a good XMPP Client for macOS which supports OTR (and is up to date).

**Comment by gretel** [comment]
switched to `telegram` secure chats and started using `signal` in addition. both work natively on osx and should be comparable to the security level of using `OTR`. there is no inter-compatibility, though.

**Comment by nsuchy** [comment]
@gretel I like that XMPP is a federated protocol. One day Signal or Telegram could run out of money and shutdown. Meanwhile XMPP will exist as long as clients are updated and someone is running servers.

**Comment by gretel** [comment]
@nsuchy before assuming things i'd suggest you actually read about the 'federation' of the telegram project, especially hinting at the "money" part.

**Comment by nsuchy** [comment]
@gretel 

Last time I used telegram, there was no way for Telegram to message non-telegram clients, at least not the same way an Email or XMPP message is.

I know Signal in the past tried to federate with another app but it slowed down their ability to roll out new features so they stopped.

**Comment by rthille** [comment]
@nsuchy https://bitbucket.org/adium/adium is the official source location now apparently.

**Comment by gretel** [comment]
@nsuchy what would be the point of telegram "supporting" XMPP? and how does email feature OTR? i am sorry but i can't follow in any reasonable way.

**Comment by nsuchy** [comment]
@gretel There is no point - they aren’t replacements for what XMPP offers.

**Comment by nsuchy** [comment]
@rthille “Last updated 2017-04-25”

**Comment by a-sn** [comment]
@nsuchy Why don't you try [Matrix](https://matrix.org)?

**Comment by nsuchy** [comment]
@a-sn because I want to use XMPP not Matrix.

**Comment by drduh** [comment]
At this point, I'm not really confident recommending any existing GUI-based XMPP/OTR application for Mac, like Adium. There's several good command-line clients that should probably go in the guide instead.

**Comment by nsuchy** [comment]
@drduh I'm interested - which CLI clients exist?

**Comment by drduh** [comment]
Here's one I've been using - https://github.com/agl/xmpp-client
