### ISSUE TITLE
Add router security to wi-fi section

### ISSUE THREAD

**Issue by a-sn** [drduh/macOS-Security-and-Privacy-Guide#303]
https://routersecurity.org
Do you think it has a place in this repo?

**Comment by mercieralex** [comment]
This is a good website with great information. Thanks for sharing!

However, in my humble opinion it is out of place in this guide.

The guide focus on security and privacy happening on your macOS device. Router security is, of course, very important —not to say primordial— but the gain is irrelevant once you leave the comfort of your home (which is a more than probable use case for MacBook) and it doesn't concern macOS directly.
