### ISSUE TITLE
broken links in macOS-Security-and-Privacy-Guide

### ISSUE THREAD

**Issue by JimLoose** [drduh/macOS-Security-and-Privacy-Guide#306]
Dead links:
http://curl.haxx.se/docs/manpage.html
http://www.securestate.com/
https://fix10.isleaked.com/
https://developer.apple.com/library/archive/documentation/Darwin/Reference/ManPages/man1/sandbox-exec.1.html

SSL Issue
https://fix-macosx.com/ (especially with curl -O https://fix-macosx.com/fix-macosx.py )

May be you should host / copy / save / cache some of those files and sites! 👍

**Comment by rthille** [comment]
http://curl.haxx.se/docs/manpage.html   works for me (but redirects to https version)
