### ISSUE TITLE
Add umask information.

### ISSUE THREAD

**Issue by vulcan25** [drduh/macOS-Security-and-Privacy-Guide#321]
As per [this guide](https://support.apple.com/en-us/HT201684) should we add advice to set the umask, with:

    sudo launchctl config user umask 077

Reboot, then confirm this has worked by executing:

    $ umask
    077

Which should return `077`.  I then create a folder in Finder, and save a file from any GUI application, and verify the permissions are set correctly:

    $ ls -ld umask*
    drwx------  2 kevin  staff       64 Dec  4 12:27 umask_testing_dir
    -rw-------@ 1 kevin  staff  2026566 Dec  4 12:28 umask_testing_file
  
This to me seems a lot safer than OSX defaults which give 'group/other' read access, and execute on directories.  In the case of a development machine, which may run something like node [(eww)](https://github.com/dominictarr/event-stream/issues/116) as a non privalleged user (You **are** running your development shit as a non-privellaged user - right?) then this would prevent processes like the webserver or app server from accessing user owned data.

Of course you'd then need to go back and `chmod` any files which already exist. Any thoughts on this?  I'd be happy to do a PR.

**Comment by HazCod** [comment]
Good finding! I've always resorted to `umask 077` in my `.bash_profile`, but that of course doesn't have any impact on Finder.

**Comment by TraderStf** [comment]
I was thinking also to this umask.
Perhaps some other folders or files could have a more strict permission, I suppose some apps might mess few things.
Any proposal?

**Comment by drduh** [comment]
It's not clear what the threat model is on a single-user system. If someone has code execution on your computer, it's not a stretch to escalate to a privileged user, especially on Macs, then file-level permissions and protections don't matter.
