### ISSUE TITLE
Merge CIS macOS 10.13 benchmark

### ISSUE THREAD

**Issue by HazCod** [drduh/macOS-Security-and-Privacy-Guide#324]
[CIS_Apple_macOS_10.13_Benchmark_v1.0.0.pdf](https://github.com/drduh/macOS-Security-and-Privacy-Guide/files/2720482/CIS_Apple_macOS_10.13_Benchmark_v1.0.0.pdf)

**Comment by HazCod** [comment]
Why was this closed @drduh ?

**Comment by drduh** [comment]
I merged the reference into Additional resources in https://github.com/drduh/macOS-Security-and-Privacy-Guide/commit/cc591e84aab04e86f06dcd0fb1cf02b6df66165a

Sorry, but I don't have time to go through and pull out individual recommendations. Feel free to do it in a PR however.
