### ISSUE TITLE
Installation alternatives not clear

### ISSUE THREAD

**Issue by joshpearce** [drduh/macOS-Security-and-Privacy-Guide#339]
I'd like to create a bootable USB installer and then re-install the OS on a MacBook Pro. But, I'd also like to completely erase the hard disk of the laptop before installing. The section on recovery partitions says I need one for FDE. But, will the USB installer create one, or do I need to do it myself beforehand?

**Comment by drduh** [comment]
I haven't done this in a while, but I don't believe the installer creates the recovery partition. You have to do it manually if you plan on using Filevault. Feel free to let us know in a pull request.
