### ISSUE TITLE
Guide to encrypted remote file store

### ISSUE THREAD

**Issue by fulldecent** [drduh/macOS-Security-and-Privacy-Guide#347]
My approach for back ups is:

- Encrypt everything before sending it
- Make incremental backups efficient

I use encfs + rsync.

Here is how if you are interested: https://gist.github.com/fulldecent/910fcd42350d59cb8558

**Comment by hazcod** [comment]
FYI there have been some issues with encfs.

**Comment by rawtaz** [comment]
Why not just use restic.net?

**Comment by fulldecent** [comment]
I'm not aware of any security concerns with encfs in the past year. The older ones have been addressed. But an alternative is gocryptfs.

Restic seems similar to Attic. That is good if you have a physical disk plugged into your network that you can mount. The rsync approach is more efficient for wifi or remote connections because you don't need to read the files off the backup disk to make a backup. The rsync server on the other end does that.

**Comment by crackhd** [comment]
> FYI there have been some security issues with encfs.

If you could provide any link would be really nice.

**Comment by hazcod** [comment]
> > FYI there have been some security issues with encfs.
> 
> If you could provide any link would be really nice.

I modified my post, granted it's for `<= 1.8` and they are now in the `1.9.x` range.

**Comment by drduh** [comment]
PRs with suggested software and methodologies are always welcome.

**Comment by fulldecent** [comment]
Thank you for the green light.

Implemented in  #357 (English) and #358 (Chinese).
