### ISSUE TITLE
FYI - Free IP tables and App

### ISSUE THREAD

**Issue by TraderStf** [drduh/macOS-Security-and-Privacy-Guide#353]
https://www.ip2location.com/free/visitor-blocker

Applications
Firewall List by Country
Firewall List by Search Engine
Redirect Visitor by Country
Traceroute
Email Tracer
Downloader Script
Extensions / Plugins
Widgets

**Comment by hazcod** [comment]
I don't see anything specific for macOS?

**Comment by drduh** [comment]
Please submit these in a PR with a brief description.
