### ISSUE TITLE
New firmwarepasswd option (-disable-reset-capability)

### ISSUE THREAD

**Issue by ajkblue** [drduh/macOS-Security-and-Privacy-Guide#354]
As of macOS 10.15 Catalina, the `firmwarepasswd` program has a new option string:
`     -disable-reset-capability       Disable firmware password reset using unlockseed`
According to [Apple's new Platform Security page](https://support.apple.com/en-gb/guide/security/sec28382c9ca/web), this effectively prevents any firmware password resets, even by Apple themselves (emphasis added):

> For users who want no one but themselves to remove their Firmware Password by software means, the -disable-reset-capability option has been added to the firmwarepasswd command-line tool in macOS 10.15. Before setting this option, users must to acknowledge that if the password is forgotten and needs removal, **_the user must bear the cost of the motherboard replacement necessary to achieve this._** 

I'm not sure of this new option strings effectiveness in the wild, but I'm sure it would be useful in the guide for locking down your Mac even more.

**Comment by drduh** [comment]
Thanks, updated in https://github.com/drduh/macOS-Security-and-Privacy-Guide/commit/7aa6381c6abcf115a0544e6943735812846545ac
