### ISSUE TITLE
Fingerprinting in Safari

### ISSUE THREAD

**Issue by SinistreCyborg** [drduh/macOS-Security-and-Privacy-Guide#367]
Hello, I'm transitioning over from Firefox to Safari due to some reasons. I used to use Privacy Badger, HTTPS Everywhere, and uBlock Origin on Firefox along with some manual changes I made to the settings to prevent canvas fingerprinting and what not.

Is there a way to achieve similar results on Safari?

**Comment by SinistreCyborg** [comment]
I use Safari Technology Preview, btw. Not sure if that changes anything.

**Comment by hazcod** [comment]
Sadly they deprecated their comparable extension API, but there are somewhat comparable ad blockers in the app store. uBlock origin lists them on their github.

**Comment by pdesjardins90** [comment]
I can recommend [DuckDuckGo's extension](https://apps.apple.com/ca/app/duckduckgo-privacy-essentials/id1482920575?l=fr&mt=12) and [Better Blocker](https://apps.apple.com/ca/app/better-blocker/id1121192229?l=fr&mt=12) for ads and trackers
