### ISSUE TITLE
Bluetooth PAN still enable when Internet Sharing was turned off on Mac OS Catalina 10.15.4

### ISSUE THREAD

**Issue by mrusli70** [drduh/macOS-Security-and-Privacy-Guide#368]
Hi

When I turn off the Internet Sharing. The selection of the Bluetooth Pan  is still enable. On macos catalina 10.15.4 and the Internet Connection sharing was not turn red. 

Is there any terminal command which i can totally turned off the bluetooth pan.

**Comment by djrobin17** [comment]
Try this if it helps - sudo networksetup -removenetworkservice "Bluetooth PAN"

**Comment by drduh** [comment]
Please send a PR if @djrobin17 advice helped with this issue.
