### ISSUE TITLE
3 questions regarding the “Recovery partition” guidance

### ISSUE THREAD

**Issue by kauniss** [drduh/macOS-Security-and-Privacy-Guide#376]
OS: 10.15.6

I’m a novice Mac user, finding it rather tricky to follow this guide. I downloaded the latest Catalina installer from the appstore, and created a bootable USB installer as per the instructions. Now, I have questions regarding the next step, regarding the “Recovery partition“.

1) Do I need to create a recovery partition when I am running Catalina? It appears there is already a built-in Recovery Drive (I have not created one).

After failing to achieve any results with the downloaded MagerValp/Create-Recovery-Partition-Installer (I opened the app, drag-and-dropped the Catalina Installer image (.app), and was ultimately greeted by “file path not found” and “Cancelled”. It’s highly likely I have erred but there’s also barely any instructions, either here or in the authors repository.

So instead I opt to do it the manual way: I downloaded the RecoveryHDUpdate, verified hashes, initiated installation. 

2) Apparently it’s a ”Lion” (10.7) Recovery update installer and so I can't install it on any partition. Is there a more recent version (eg. a “Catalina Recovery Update Installer”) available?

Further down under the same heading in your guidance, I read “expand the installer, then run it - again ensuring /Volumes/macOS path is the **newly created partition** on the connected disk”.

3) ... which newly created partition? When was I supposed to create a partition? This is not clear. As I went from the "Bootable USB installer" step to "Recovery Partition there is no clarity about this. And I assume the "connected disk" refer to the one I am using and planning on erasing + installing a new copy of Catalina on.  So if this is the case, do I simply create a partition in Disk Utility pre-erasure? How big should the partition be?

Sorry, I’m an amateur Mac / computer user in general and just need someone to explain this in baby language to me. Would be much appreciated.

**Comment by drduh** [comment]
Resolving to inactivity and likely outdated information by now.
