### ISSUE TITLE
Confusion about certificates

### ISSUE THREAD

**Issue by Kali-Lionbrine** [drduh/macOS-Security-and-Privacy-Guide#384]
The section on "Certificate authorities" is not clear on what certificates should be set to "Not Trusted". Certificates are not well explained in this section, however after some research I understand the power they hold. I am afraid disabling every trusted certificate in this section could lead to problems trying to load websites or software? 

tldr:
Should we Not Trust **Every Certificate** in the "System Roots Tab"?
Could doing this result in issues?

**Comment by drduh** [comment]
Revoking trust to needful CAs should be pretty obvious - sites won't load, software may not connect, etc. The exercise is left to the reader to decide which CAs are needed and which to trust, but in general its safe to prune at least a dozen or more obviously useless certs.

**Comment by acmpo6ou** [comment]
I'm also unsure which certs to remove. @drduh, can you tell us which certs you have removed? Or maybe, if it's easier, which certificates you have left turned on?
I turned off some certs from Apple, Amazon, and Microsoft, but there are others. I've no idea which I should trust
