### ISSUE TITLE
check validity of certificates

### ISSUE THREAD

**Issue by jotulaja1** [drduh/macOS-Security-and-Privacy-Guide#387]
I frequently find `trustd` connecting to apple servers (over port 443) and to CheckPath servers (over port 80). Port 80 doesn't seem to be too good to use.

I would like to know whether there is a way to verify which certificates are valid quickly.

Is there any application that would let me do that quickly?

**Comment by drduh** [comment]
You can check validity with `sslscan` but I believe `trustd` is actually doing revocation checks - unsure of whether it leaves a log, but you can use https://crt.sh/ to check on certs.
