### ISSUE TITLE
Request - add explanation of why Safari Tech Preview is preferred over Safari

### ISSUE THREAD

**Issue by tillydray** [drduh/macOS-Security-and-Privacy-Guide#392]
> The Safari channel that follows a six-week release cycle (similar to as Chrome and Firefox) is called Safari Technology Preview and it is the recommended option instead of the stable channel of Safari.

I assume the reasoning is that STP gets updates more frequently, but it isn't clear to me if it gets security updates more frequently than Safari. However, it could be getting bugs added more frequently 😆

**Comment by kimg45** [comment]
I think it would be best to recommend people stay on stable Safari as beta software can introduce bugs/vulnerabilities that get fixed before the stable release.

**Comment by beerisgood** [comment]
Since nearly 2 years I check every Safari preview release notes and never read anything about fixed security or privacy stuff. Only new features and some „normal“ fixes. 

Nothing important for normal user.

**Comment by drduh** [comment]
I removed the tech preview recommendation. The browser section could use additional citations and review.
