### ISSUE TITLE
Apple M1 // MDM for Privacy // CoreDuet / Siri horrible tracking

### ISSUE THREAD

**Issue by ink-splatters** [drduh/macOS-Security-and-Privacy-Guide#395]
Hi,

thanks for great guide. I’ve one comment and questions:

* Apple M1 is not mentioned here…or maybe I’m missing it? If I’m correct, Mojave method is not applicable for Apple Silicon. There is iOS like hardened boot process (refer to great @howardnoakley blog [eclecticlight.co](https://eclecticlight.co) 
* can you comment on using MDM for at least basic privacy hardening: [https://support.apple.com/en-gb/guide/deployment/dep0f7dd3d8/web](https://support.apple.com/en-gb/guide/deployment/dep0f7dd3d8/web) - that’s about iOS but i suppose to some extent it’s applicable to macOS as well
* any ideas how to get rid of horrid tracking like siri/CoreDuet ‘knowledgeC’ database and maybe more, without compromising SSV?

Kind regards,
Peter

**Comment by beerisgood** [comment]
> * any ideas how to get rid of horrid tracking like siri/CoreDuet ‘knowledgeC’ database and maybe more, without compromising SSV?

What? Siri does not track you. All data remains local to your device as long as you do not say "hey siri" - provided you have set up Siri on your device.
CoreDuet [is](https://origin-discussions-us.apple.com/thread/6996019?answerId=28075156022#28075156022) a process related to Handoff and not any kind of tracking.
