### ISSUE TITLE
Command line instruction to download iso from iOS

### ISSUE THREAD

**Issue by Unitiser** [drduh/macOS-Security-and-Privacy-Guide#397]
Hello,

To me, downloading the installer to create the usb was very confusing. For some reason, the installer wouldn't show up on the appstore or on any other Apple web site.

The technique described here `https://osxdaily.com/2020/04/13/how-download-full-macos-installer-terminal/` using `softwareupdate` is super straight forward. I believe these commands could be mentionned somewhere in the guide : 

```
softwareupdate --list-full-installers
softwareupdate --fetch-full-installer --full-installer-version x.x.x
```

**Comment by drduh** [comment]
@Unitiser that's a great tip - can you send a PR to include it?
