### ISSUE TITLE
Version Consistency Across the Guide: What's the Latest Supported?

### ISSUE THREAD

**Issue by johnsoga** [drduh/macOS-Security-and-Privacy-Guide#399]
Going through the guide I notice a reference to "download" Mojave, instructions for creating an installer using Catalina, creating a recovery partition using Lion, etc. Is there any idea on to stick to a "latest" version and perhaps note changes for older versions where known/applicable, or have all documentation only relevant for a certain version and versions later than it? I imagine at some point it maybe become hard to maintain otherwise as there will likely be several references that accumulate over time for the various releases and their potentially individual nuances.

**Comment by drduh** [comment]
We should try to keep the guide up to date to be relevant for security and not let it become a historical accumulation of now-useless facts. I believe Apple supports the two most recent macOS releases with security updates - we should follow this model.

**Comment by beerisgood** [comment]
> I believe Apple supports the two most recent macOS releases with security updates - we should follow this model.

That’s not fully true as you can read in news. Only Monterey is completely patched so using the latest version is the only recommended  recommendation

**Comment by drduh** [comment]
We should cite any supporting evidence either way; I agree clarifying this is important for the guide. Most security guidelines should have a "best by" expiration date in general.

**Comment by kimg45** [comment]
I'd be happy to go through and update the guide. I'd like to first go through and remove any dead/outdated links, then remove anything that's only relevant to EOL versions of macOS or the hardware. I also noticed quite a bit of software that's recommended hasn't seen an update in multiple years on some cases, I believe these should be removed as running abandonware is a huge security risk.

**Comment by drduh** [comment]
I removed several outdated references, there are likely plenty more to go. The firmware/hardware sections definitely need revision, see #411
