### ISSUE TITLE
Question: Why remove the admin account from FileVault?

### ISSUE THREAD

**Issue by halo** [drduh/macOS-Security-and-Privacy-Guide#408]
I have difficulties wrapping my head around [this recommendation](https://github.com/drduh/macOS-Security-and-Privacy-Guide/commit/0bb911d4ba7df9bf7e9a274edf6efd5f2e41f6f0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R344):

> The admin account can also be removed from FileVault.

What is the benefit of not being able to unlock the disk using the administrator account? I thought the admin account is supposed to be more difficult to be compromised than the normal user account. So why would only the user account get the FileVault key?

I *think* I understand the technical details, but don't understand the threat scenario. I would appreciate any clarification.

Thank you for your time 🙂

**Comment by drduh** [comment]
I can't think of any particularly strong reason to do this, other than as a general separation of privilege, but even then the risk is difficult to comprehend. Feel free to remove or change that directive.

**Comment by beerisgood** [comment]
Also from https://support.apple.com/HT203998

> If FileVault is enabled, a hidden user may continue to appear in the initial login window after the computer is turned on or restarted.

which leads the whole thing ad absurdum

**Comment by drduh** [comment]
Thanks for the fix!
