### ISSUE TITLE
Add BusKill

### ISSUE THREAD

**Issue by maltfield** [drduh/macOS-Security-and-Privacy-Guide#418]
BusKill is a cross-platform, open-source hardware and software project that uses a hardware tripwire/dead-man-switch (a usb cable with a magnetic breakaway) to trigger your computer to lock or shutdown if the user is physically separated from their machine.

 * https://github.com/BusKill/buskill-app

Please consider adding a link to [BusKill](https://github.com/buskill/buskill-app) in your [Physical access](https://github.com/drduh/macOS-Security-and-Privacy-Guide#physical-access) section, next to the mention of usbkill (which hasn't been updated in over 6 years).

**Comment by drduh** [comment]
Looks cool - @maltfield want to propose a PR with it and some section cleanup?

**Comment by maltfield** [comment]
@drduh sure, please see PR:

 * https://github.com/drduh/macOS-Security-and-Privacy-Guide/pull/419

**Comment by drduh** [comment]
Nice! Thank you!
