### ISSUE TITLE
Update to include Brave Browser?

### ISSUE THREAD

**Issue by ghost** [drduh/macOS-Security-and-Privacy-Guide#424]
Brave Browser was once obscure in terms of usage but surely it's popular enough now to warrant a more detailed mention in the browser section?

**Comment by beerisgood** [comment]
I don’t see any advantage compared with Safari but many disadvantages like unique fingerprint and less security and privacy

**Comment by drduh** [comment]
Anyone is welcome to include other browsers on their own justified merit with a PR.
