### ISSUE TITLE
Little Snitch & Steven Black Host

### ISSUE THREAD

**Issue by leohidalgo** [drduh/macOS-Security-and-Privacy-Guide#431]
In the guide there is mention of **Little Snitch** & **Steven Black Host**, I have created a repository that generates little snitch rules from **Steven Black Host** files, these are generated every 12 hrs whenever there is a change within the source.

This is generated with github action automatically.

I don't know if we can include in the guide.

Repository: https://github.com/leohidalgo/little-snitch---rule-groups

**Comment by leohidalgo** [comment]
What do you think @drduh? do I create a PR with it?

**Comment by drduh** [comment]
That sounds great, go ahead and link to it in the relevant section!

**Comment by leohidalgo** [comment]
I don't know if I should add in the `Third party firewalls` section or in the `Host file` section.
