### ISSUE TITLE
read_launch_plists.py Throws an Error

### ISSUE THREAD

**Issue by kimg45** [drduh/macOS-Security-and-Privacy-Guide#466]
Error is in line 87:  iterator should return strings, not bytes (did you open the file in text mode?)

Tested in a VM, so it's the default experience if you open on the stock OS. Also I'm using the version of python that comes with the dev tools. I think a script like this ought to work OOTB.

**Comment by drduh** [comment]
I am not even sure the launchd stuff is useful anymore, as it was implemented long before SIP and other protections, features and startup methods existed. The guide no longer has references to any of the files either. The Services section probably needs a refresh and, as part of it, we can decide to fix or remove these files. What do you think?

**Comment by kimg45** [comment]
Yeah if it was up to me I would just remove it.
