### ISSUE TITLE
Bluetooth on off in mac os

### ISSUE THREAD

**Issue by sooryakants** [drduh/macOS-Security-and-Privacy-Guide#472]
i want to any idea open and close the bluetooth with the help of code and command. provide the solution .

**Comment by kimg45** [comment]
I don't think there's a Terminal command to do it without third party software. You can easily enable/disable Bluetooth with a [shortcut](https://support.apple.com/guide/shortcuts-mac/launch-a-shortcut-from-another-app-apd163eb9f95/7.0/mac/14.0#apd94a0e7c32) which can be tied to a keyboard shortcut or almost any other way you might want to trigger it.
